### ISSUE TITLE
error 1146 table doesn't exist

### ISSUE THREAD

**Issue by micker** [joomla-extensions/patchtester#106]
after patcher installation (beta3)
going to component
i have this error
Table 'flexidev.kfqt8_patchtester_pulls' doesn't exist SQL=SELECT COUNT(*) FROM `kfqt8_patchtester_pulls` AS `a` LEFT JOIN `kfqt8_patchtester_tests` AS `t` ON t.pull_id = a.pull_id

**Comment by photodude** [comment]
Have you tried Beta 4? I can't confirm this issue, it almost seems like an install error.
