### ISSUE TITLE
patch tester broke after searching a word

### ISSUE THREAD

**Issue by peteruoi** [joomla-extensions/patchtester#107]
An error has occurred.
 1054 Unknown column 'Ajaxifying' in 'where clause' SQL=

```sql
SELECT COUNT(*) FROM `fxowe_patchtester_pulls` AS `a` LEFT JOIN `fxowe_patchtester_tests` AS `t` ON t.pull_id = a.pull_id WHERE (`a`.`title` LIKE '%Ajaxifying%') OR (`a`.`pull_id` = Ajaxifying)
```

joomla 3.4.5
xamp 3.2.1

**Comment by schnuti** [comment]
I entered the search the "Joomla" way id:8256 
1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':8256)' at line 4 SQL=SELECT COUNT(*) FROM `iclb8_patchtester_pulls` AS `a` LEFT JOIN `iclb8_patchtester_tests` AS `t` ON t.pull_id = a.pull_id WHERE (`a`.`title` LIKE '%id:8256%') OR (`a`.`pull_id` = id:8256)

**Comment by zero-24** [comment]
Can you try #108 ?
