### ISSUE TITLE
Error fetching GitHub Data

### ISSUE THREAD

**Issue by Gerlof** [joomla-extensions/patchtester#110]
I get this error message after clicking button [Fetch Data] using Joomla 3.5.0 beta:
>Processing data from GitHub
Error inserting pull request data into the database: Unknown column 'sha' in 'field list' SQL=INSERT INTO `#__patchtester_pulls` (`pull_id`,`title`,`description`,`pull_url`,`sha`) VALUES (8619,'Improvements for secure registration and login','Assume the following setup:\r\n* the webserver can be reached via HTTP and HTTPS\r\n* the backend is...','https://github.com/joomla/joomla-cms/pull/8619','74d4c4b360cdd728160b6cef274508877aba63dc'),

(pasting just a part of the error message)

**Comment by mbabker** [comment]
Is this a fresh install?  Upgrades between beta releases is not supported; you'll need to uninstall and reinstall the component.

**Comment by Gerlof** [comment]
@mbabker OK, i'll try that! Thanks for the quick reply ;)
