### ISSUE TITLE
Problems with open_basedir and redirect

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-extensions/patchtester#111]
I installed the patch tester and after a sucessull instal i can't apply any patch,, everything else works fine.
There is no error message just:
```
Message
There are no files to patch from this pull request. This may mean that the files in the pull request are not present in your installation.
```

The problem seems to be in 
https://github.com/joomla-extensions/patchtester/blob/master/administrator/components/com_patchtester/PatchTester/Model/PullModel.php#L174

I investigated the problem and the problem in the diff url `$pull->diff_url` is a redirect to another URI.
Example: https://github.com/joomla/joomla-cms/pull/8645.diff to https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/8645.diff

By forcing the follow location (follow redirects) in curl JHttpFactory `$options[CURLOPT_FOLLOWLOCATION] = 1;` it works.
See https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/http/transport/curl.php#L160-L163

My PHP (5.6.x) config has `open_basedir` enabled and that seems to be the problem.

An aditional note:
As of PHP 5.6+ curl follow location already work with open_basedir and safe_mode.
http://php.net/ChangeLog-5.php
`Implemented FR #65646 (re-enable CURLOPT_FOLLOWLOCATION with open_basedir or safe_mode).`

@mbabker can you check?

And, of course, thanks for all your work in Joomla

**Comment by mbabker** [comment]
The check is required due to https://github.com/joomla/joomla-cms/pull/3534

At best, a patch can be proposed for the CMS to change the if conditional to this to allow PHP 5.6 to have the option set correctly:

```php
if (version_compare(PHP_VERSION, '5.6', 'ge') || (!ini_get('safe_mode') && !ini_get('open_basedir'))) {
    // ...
}
```

Closing as this isn't an issue with the patchtester component itself but rather one of its upstream dependencies.

**Comment by andrepereiradasilva** [comment]
ok i will create a patch in joomla
