### ISSUE TITLE
[Features] Show tags and link to travis

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-extensions/patchtester#112]
This is a feature request for the patch testar to show in the list the PR github tags.

Of particullary useful is to show the "RTC" tag so we immediately  know it already passed the human tests.
Or in alternative show travis and human tests current results.

A column with latest travis results and link to it would be cool too.

Just suggestions.

**Comment by mbabker** [comment]
See https://github.com/joomla-extensions/patchtester/issues/88
