### ISSUE TITLE
Unable to search/filter by Pull ID

### ISSUE THREAD

**Issue by photodude** [joomla-extensions/patchtester#117]
All attempts to search/filter by Pull ID result in "No Matching Results" (even when I am looking right at the pull id I search for) with the current release Patch Tester 2.0.0.beta4

**Comment by mbabker** [comment]
Enable debug mode and check what queries are being made.  That should help identify the issue.

**Comment by photodude** [comment]
Maybe this is the source?
![patcherror](https://cloud.githubusercontent.com/assets/10253980/11848143/26689c20-a3de-11e5-92fb-82ad8ee464a6.PNG)

**Comment by mbabker** [comment]
The query's right.  For your filter it is looking for titles containing `5837`.  If you want to look it up by ID, use `id:5837` in the filter box (the same way most core components work).

**Comment by photodude** [comment]
Generally I consider requiring additional perimeters for a search field questionable for UI/UX.
An `OR` in the query should allow for searching by either title or ID without needing the additional prefix.
There is also no tool tip or other information specifying the necessity of a prefix for ID searching.

Generally speaking I doubt most people are searching core components by ID, although the tool tip does specify the prefix as an option.

**Comment by mbabker** [comment]
It was done differently before (see https://github.com/joomla-extensions/patchtester/commit/76de1805ff2f8a7a5c18fdb0ba799d480d1f9927 which changed it to follow the core convention), but that caused issues too.  Updating the tooltip or adding the is_numeric check isn't a major issue I'd say.
