### ISSUE TITLE
Slashes in password => Malformed

### ISSUE THREAD

**Issue by grhcj** [joomla-extensions/patchtester#122]
When you use a GitHub password containing slashes for the patchtester component, the message "Could not connect to GitHub: malformed" appears.

**Comment by mbabker** [comment]
It's an underlying issue with the Joomla libraries.  The JGithub library was patched to deal with `@` in passwords but the underlying library supporting that needs a proper global fix to ensure all characters are being correctly processed.  See my feedback on this pull request: https://github.com/joomla/joomla-cms/pull/6734
