### ISSUE TITLE
RFC: Button to submit test results including system info

### ISSUE THREAD

**Issue by richard67** [joomla-extensions/patchtester#125]
Wouldn't it be nice to have a button to submitt the test results after having tested a PR?

It could make a popup (modal) appear where user can set the result and check a check box to include the system info as text, as it will be possible with Joomla! 3.5.

Or mayve even always include some of the system info, like PHP version, database server type and version, database client library type and version?

**Comment by mbabker** [comment]
https://github.com/joomla/jissues/issues/623

**Comment by richard67** [comment]
Ah, duplicate, I'll close.
