### ISSUE TITLE
Searching by ID doesn't work?

### ISSUE THREAD

**Issue by MATsxm** [joomla-extensions/patchtester#128]
#### Steps to reproduce the issue
Searching for he Pull ID 9365 wich does exist

#### Expected result
The Pull with the ID 9365 to appear as a result

#### Actual result
the "No Matching Results" appears as the result

#### System information (as much as possible)
Patch Tester 2.0.0.beta4

**Comment by mbabker** [comment]
Already fixed.

Search with the `id:9365` syntax or by the title.  If I remember I'll package a new version this weekend.

**Comment by MATsxm** [comment]
thanks :+1:
