### ISSUE TITLE
Can't apply patch (with PDO driver in MySQL 5.6.6+)

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-extensions/patchtester#129]
#### Steps to reproduce the issue

Use with PDO driver in MySQL 5.6.6+
Try to apply a patch.

#### Expected result

Patch applied.

#### Actual result

SQLSTATE[HY000]: General error: 1364 Field 'comments' doesn't have a default value

**Comment by mbabker** [comment]
Dropped the column for now as it's unused.
