### ISSUE TITLE
Error Display after using joomla patchtester 2-3 times.

### ISSUE THREAD

**Issue by shubhamnba2009** [joomla-extensions/patchtester#145]
#### Steps to reproduce the issue
1.Install joomla patchtester.
2.Use it 2-3 times

#### Expected result
It should open patchtester menu everytime

#### Actual result
After using 2-3 times it shows:
( ! ) Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\manilor\libraries\joomla\http\transport\curl.php on line 185
Call Stack
#	Time	Memory	Function	Location
1	0.0020	140048	{main}( )	..\index.php:0
2	0.1530	2512064	JApplicationCms->execute( )	..\index.php:51
3	0.1530	2512216	JApplicationAdministrator->doExecute( )	..\cms.php:257
4	0.2316	3835784	JApplicationAdministrator->dispatch( )	..\administrator.php:152
5	0.2679	4079960	JComponentHelper::renderComponent( )	..\administrator.php:98
6	0.2724	4093328	JComponentHelper::executeComponent( )	..\helper.php:380
7	0.2729	4114912	require_once( 'C:\xampp\htdocs\manilor\administrator\components\com_patchtester\patchtester.php' )	..\helper.php:405
8	0.2862	4305744	JControllerLegacy->execute( )	..\patchtester.php:20
9	0.2862	4305928	JControllerLegacy->display( )	..\legacy.php:728
10	1.9358	4935088	PatchtesterViewPulls->display( )	..\legacy.php:690
11	1.9479	4936928	JViewLegacy->get( )	..\view.html.php:91
12	1.9481	4937168	PatchtesterModelPulls->getItems( )	..\legacy.php:401
13	1.9492	4938816	PatchtesterModelPulls->requestFromGithub( )	..\pulls.php:184
14	8.7684	5107512	JGithubPackagePulls->getList( )	..\pulls.php:224
15	8.7695	5107944	JHttp->get( )	..\pulls.php:302
16	8.7702	5108832	JHttpTransportCurl->request( )	..\http.php:175

#### System information (as much as possible)
OS Windows
 PHP 5.6.15
 MySQLi 5.5.5-10.1.9-MariaDB
Joomla 3.5.1

**Comment by mbabker** [comment]
That code stack comes from a heavily dated version of the patch tester.
The current version doesn't use the legacy MVC layer.  Please test with the
release candidate.

**Comment by shubhamnba2009** [comment]
I just uninstalled the patchtester version in my latest staging
And installed latest Patch Tester 2.0.0 Release Candidate. 
Now when i click the fetch data button it opens up Fetching github data dialogue box after 10-20 sec it displays the same error as i mentioned above.
Any suggestions on that?

**Comment by shubhamnba2009** [comment]
Ahhaa... I don't know what happened.After writing the above comment when i returened back to the administartor back-end it displayed all the issues.
Now i think the problem is solved.
Thanks for the help mbabker :+1:

**Comment by brianteeman** [comment]
Can be closed
