### ISSUE TITLE
[hathor] reset icon missing

### ISSUE THREAD

**Issue by brianteeman** [joomla-extensions/patchtester#147]
In hathor it is trying to use icon-32-expired for the reset button but that doesnt exist

**Comment by mbabker** [comment]
There's a part of me that wants to say "won't fix".  The Hathor overrides need a CSS definition mapping the `icon-32-expired` class to the `icon-32-revert` class (and to make things even more ironic there isn't an `icon-revert` in the IcoMoon set).

**Comment by brianteeman** [comment]
You could use icon deny.

But I probably wouldn't bother to fix it either as its not the only thing
missing an icon with hathor

**Comment by mbabker** [comment]
There's no deny icon in IcoMoon either.  The only icon I found that's in both is the purge icon, but that makes it a trash can with IcoMoon.
