### ISSUE TITLE
GitHub link goes to API

### ISSUE THREAD

**Issue by Bakual** [joomla-extensions/patchtester#148]
#### Steps to reproduce the issue
Click the "GitHub" button for a patch in the Patchtester list. It will open a new tab with some JSON response.

#### Expected result
Should go to the GitHub PullRequest page (eg https://github.com/joomla/joomla-cms/pull/9896)

#### Actual result
Opens the JSON API page (eg https://api.github.com/repos/joomla/joomla-cms/pulls/9896)

**Comment by mbabker** [comment]
Already fixed with 459f643957f81a45b5ac528b8d8d016d3a24b441

**Comment by Bakual** [comment]
Perfect :+1:
