### ISSUE TITLE
link to github starts with api.

### ISSUE THREAD

**Issue by slibbe** [joomla-extensions/patchtester#150]
#### Steps to reproduce the issue
When clicking on the Github link for a certain issue with Patchtester 2.0.0.rc	27-March-2016, the url has the following structure https://api.github.com/repos/joomla/joomla-cms/pulls/nnnn

This gives the info but in a rather unreadable format

#### Expected result
Human readable and formatted page with info on the issue at hand.

#### Actual result
Unreadable stream of JSON output

#### System information (as much as possible)
PatchTester 	2.0.0.rc	27-March-2016, ScotchBox 2.5 .
[systeminfo-2016-04-15T13-05-11+00-00.txt](https://github.com/joomla-extensions/patchtester/files/221024/systeminfo-2016-04-15T13-05-11.00-00.txt)

**Comment by mbabker** [comment]
This is already fixed, see #142

**Comment by slibbe** [comment]
Ok, cool. So which version of the Patchtester should I use now? I downloaded used version just an hour ago.

**Comment by mbabker** [comment]
Still use the latest RC.  I haven't had reliable internet for the last week to build another package.  Just click the link for the Joomla issue tracker instead of the GitHub link for now (the issue tracker also has a direct link to GitHub).
