### ISSUE TITLE
Make more filters possible

### ISSUE THREAD

**Issue by conconnl** [joomla-extensions/patchtester#151]
It's very difficult to find issues in the PatchTester which are **not** open for review at CMS Maintenainers.
We only have the ability to filter on _"Ready to commit"_

Please add more filters.
We are now clicking on multiple issues and checking the status and labels, to see if we can test a issue.

<img width="1403" alt="screen shot 2016-04-15 at 16 41 47" src="https://cloud.githubusercontent.com/assets/11913918/14564934/fa85995a-0328-11e6-9302-e3ecc5aa5db2.png">

<img width="188" alt="screen shot 2016-04-15 at 16 34 24" src="https://cloud.githubusercontent.com/assets/11913918/14564911/e871688e-0328-11e6-819c-c576390f6ce9.png">

**Comment by mbabker** [comment]
Needs https://github.com/joomla-extensions/patchtester/issues/65 to be done.  The statuses aren't on GitHub, which is where the patch tester is pulling all data from right now.  So until there's a consistent way to pull all the needed data from the issue tracker, unfortunately what you're doing now is the "best" option.
