### ISSUE TITLE
Fatal error: Allowed memory size of 268435456 bytes exhausted

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-extensions/patchtester#162]
#### Steps to reproduce the issue

When apliyng a patch with a lot of files i get a memory exausted fatal error.

This is the patch i'm applying https://github.com/infograf768/joomla-cms/pull/30

#### Expected result

Patch applied.

#### Actual result

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 4078152 bytes) in /path/to/joomla-staging/libraries/joomla/database/driver.php on line 2041

#### System information (as much as possible)

Joomla 3.6.0 beta 2
PHP memory limit 256M.

#### Additional comments

I know i can put the php memory limit higher.

But this is the memory limit i used for joomla forever and always worked.
So why is the patchtester using so much memory.

**Comment by andrepereiradasilva** [comment]
just tested with 350MB and still get the fatal error
Fatal error: Allowed memory size of 367001600 bytes exhausted (tried to allocate 4078152 bytes) in /path/to/joomla-staging/libraries/joomla/database/driver.php on line 2041

**Comment by andrepereiradasilva** [comment]
Aditional info.
If i removed this lines https://github.com/joomla-extensions/patchtester/blob/master/administrator/components/com_patchtester/PatchTester/Model/PullModel.php#L297-L309 it applies with no memory issues (of course it doesn't save as applied).

So the problem should be there.

**Comment by mbabker** [comment]
I removed JTable completely.  So we'll see how much that helps.

**Comment by andrepereiradasilva** [comment]
ok thanks!

**Comment by mbabker** [comment]
Have you had a chance to test perhaps?  Between this and other changes I made today, a lot of moving pieces in the code right now.

**Comment by andrepereiradasilva** [comment]
i tested the same patch and worked now. thanks.
