### ISSUE TITLE
Could not connect to github error.

### ISSUE THREAD

**Issue by shubhamnba2009** [joomla-extensions/patchtester#165]
#### Steps to reproduce the issue
Search for particular issue in joomla patchtester extension
List comes
Select apply patch

#### Expected result
Patch should be applied

#### Actual result
Following error comes
![errorpatch](https://cloud.githubusercontent.com/assets/12000068/16541471/8f39de66-40a1-11e6-8e62-2ea909ef944c.png)

#### System information (as much as possible)
Joomla 3.6.0-beta2
Server: 127.0.0.1 via TCP/IP
Server type: MariaDB
Server version: 10.1.13-MariaDB - mariadb.org binary distribution
Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.21
PHP extension: mysqli Documentation
PHP version: 5.6.21

**Comment by MATsxm** [comment]
Not able to reproduce even if the issue #10881 took a long time to load.

Did you tried with your GitHub credentials filled ('**Options**' btn)?

**Comment by shubhamnba2009** [comment]
Yes I have filled out the credentials under options button
Selected github repository:Joomla CMS under github repository tab

**Comment by shubhamnba2009** [comment]
And this error occurs with every patch I try to apply
