### ISSUE TITLE
Patches can not be reverted properly

### ISSUE THREAD

**Issue by coaleb** [joomla-extensions/patchtester#166]
I don't know if this has always been the case with Patch Tester, but when you apply patches, it is unable to revert the changes. In my specific case:

I applied PR 10391, it applied successfully, but since I was just 'testing' I clicked revert to revert the changes made by the PR.

The expected result was that the PR would revert and all is forgiven.

The actual result was this error:
PatchTester\Model\PullModel::revert - Error retrieving table data ([])

...and the patch is still applied.

Joomla 3.6.0 Stable
Patch Tester 3.0.0 Alpha
PHP 5.5.36
MySQL 5.5.45-cll-lve
Apache/2.4.18

In a side note, I did not actually intend to test this PR, the only reason I applied it was because I was trying to see if ANYTHING would apply. Every PR I attempted to apply prior to this one resulted in this error:
"Could not connect to GitHub: No commit found for the ref [ref...]"

**Comment by mbabker** [comment]
Please use the stable package unless you're purposefully trying to test the
new version.  There's been a couple of bug fixes since the alpha tag and
it's definitely not battle tested yet.

**Comment by coaleb** [comment]
Got it. I was actually trying to test a PR, so I went back to the stable version, and everything worked great. Thanks for the heads up!
