### ISSUE TITLE
Can't fetch data

### ISSUE THREAD

**Issue by Sandra97** [joomla-extensions/patchtester#167]
#### Steps to reproduce the issue
Install com_patchtester
Click on Fetch Data

#### Expected result
Being able to fetch data and test PR

#### Actual result
![joomla patch tester - joomla 3 6](https://cloud.githubusercontent.com/assets/4682328/16900342/8dfd9bd2-4bf0-11e6-9d01-12b04d25675f.png)

#### System information (as much as possible)
On Windows
Joomla! 3.6.0
PHP 7.0.4
Cache disabled
Patch Tester 2.0.1

**Comment by mbabker** [comment]
Assuming I've translated the French part of that correctly, it's saying the `is_rtc` column doesn't exist in your database.  It does exist in the SQL schema though so it should have been added correctly.  Either check the database to make sure it exists or try uninstalling and reinstalling to fix the database.

**Comment by Sandra97** [comment]
Followed your advice, so of course now it works fine. Thank you!
