### ISSUE TITLE
 Error: Could not connect to GitHub with 3.0.0-alpha

### ISSUE THREAD

**Issue by Lavsteph** [joomla-extensions/patchtester#168]
#### Steps to reproduce the issue
1 - GitHub authentication
![login](http://img4.hostingpics.net/pics/439295JoomlaPatchTesterSettingsDeveloppementAdministrationMozillaFirefox021.png "login github")
2 - Apply patch : error to connect to Github
#### Actual result
for exemple
![](http://img4.hostingpics.net/pics/757726JoomlaPatchTesterDeveloppementAdministrationMozillaFirefox022.png "error")

#### System information (as much as possible)
PHP Built On Linux servv16232.srv.odns.fr 2.6.32-042stab113.11 #1 SMP Fri Dec 18 17:32:04 MSK 2015 x86_64
Database Version 5.5.43-37.2
Database Collation utf8_general_ci
Database Connection Collation utf8mb4_general_ci
PHP Version 5.6.24
Web Server Apache 2.4.23
WebServer to PHP Interface cgi-fcgi
Joomla! Version Joomla! 3.6.1-rc1 Release Candidate [ Noether ] 28-July-2016 23:25 GMT
Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 
User Agent Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by MATsxm** [comment]
Should be related to #165

**Comment by mbabker** [comment]
Already fixed in master
