### ISSUE TITLE
Cant find commit

### ISSUE THREAD

**Issue by brianteeman** [joomla-extensions/patchtester#171]
#### Steps to reproduce the issue

I just upgraded from 2.00rc to 3.0 and now I am getting  lot of 

> Could not connect to GitHub: No commit found for the ref username

They work fine with 2.00

**Comment by zero-24** [comment]
Can you try the last alpha IIRC this got fixed there.

**Comment by brianteeman** [comment]
I was using the latest alpha - downloaded from https://github.com/joomla-extensions/patchtester/releases about 30 minutes ago
