### ISSUE TITLE
Rename files don't works correct anytime

### ISSUE THREAD

**Issue by zero-24** [joomla-extensions/patchtester#172]
#### Steps to reproduce the issue

- install 4.0.0
- install last version of patchtester
- try to install https://github.com/joomla/joomla-cms/pull/12132
- try to send a mail with the send mail buton
- it fails
- look at https://github.com/mbabker/joomla-cms/blob/PHPMailer-6.0/libraries/vendor/phpmailer/phpmailer/src/
- and comepare it with your dir
- you see the PHPMailer.php is missing
- have a look at the PR
- this file gots renamed in the PR but not on your site

#### Expected result

Patch successfull applyed

#### Actual result

Patch not successfull applyed

#### System information (as much as possible)

- J4.0.0
- last patchtester

**Comment by mbabker** [comment]
The first pass at support for renamed files is in the code now.

**Comment by zero-24** [comment]
Thanks!
