### ISSUE TITLE
4.0 Error

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-extensions/patchtester#173]
#### Steps to reproduce the issue

Use patchtester on 4.0

#### Expected result

works

#### Actual result

Use patchtest0 Argument 2 passed to PatchTester\Controller\AbstractController::__construct() must be an instance of JApplicationBase, instance of JApplicationAdministrator given, called in /path/to/joomla-400/administrator/components/com_patchtester/patchtester.php on line 41
er on 4.0

#### System information (as much as possible)

Latets 4.0

#### Additional comments

none

**Comment by mbabker** [comment]
See #174 which depends on https://github.com/joomla/joomla-cms/pull/12650
