### ISSUE TITLE
patchtester gives error (after fetch data) when using postgresql

### ISSUE THREAD

**Issue by slibbe** [joomla-extensions/patchtester#175]
#### Steps to reproduce the issue
Joomla 3.7.0-dev with Postgresql
Install Patchtester 3.0.0 Beta
Go to Component Patchtester
Fetch data (if you get this far)

#### Expected result
Modal view Window after fetching data

#### Actual result
An error has occurred.
0 ERROR: operator does not exist: bigint ~~ unknown LINE 4: WHERE a.pull_id LIKE '%8825%' ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.

#### System information (as much as possible)
See attachment.

#### Additional comments
Using ScotchBox 2.5 on Vagrant.

[systeminfo-2016-11-04T15-26-18+00-00.txt](https://github.com/joomla-extensions/patchtester/files/571897/systeminfo-2016-11-04T15-26-18.00-00.txt)

**Comment by mbabker** [comment]
@alikon any suggestions?

**Comment by alikon** [comment]
there is a mysql dialect query, should be  fixed with #176

**Comment by mbabker** [comment]
Thanks!
