### ISSUE TITLE
3.0 beta not all files patched/added

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-extensions/patchtester#179]
Use 3.0 beta with https://github.com/joomla/joomla-cms/pull/11834

Noticed that not all files where patched/created: at least the folder and files under plugins/system/userlogs/ where not created.

cannot really say what the bug is.

Additional note:
In the same patch in 2.0.1 i got Fatal error: Allowed memory size of 367001600 bytes exhausted (tried to allocate 3658768 bytes) in /path/to/joomla-staging/libraries/joomla/database/driver.php on line 2041

**Comment by roland-d** [comment]
@andrepereiradasilva Given how old this is and I can't find any other PR that is of this size. Let's revisit this if we have another PR of this size or when the problem manifests it again.
