### ISSUE TITLE
URL Malformed (Patchtester 3.0.0 Beta and 2.0.1 stable)

### ISSUE THREAD

**Issue by AMurray2016** [joomla-extensions/patchtester#180]
#### Steps to reproduce the issue
Essentially have followed the instructions here:
https://docs.joomla.org/Testing_Joomla!_patches
Installed Patchtester through Extension Manager - installation works fine
Entered Github  U/N and P/W under "Options" (not using 2FA).
Click Joomla! Patch Tester on Component Menu
Click Fetch Data button in the component.

#### Expected result
Expect Patchtester to load the Github issues.

#### Actual result
Error message:
An error has occurred.     0 <url> malformed   Return to Control Panel

#### System information (as much as possible)
Windows 7 Home Premium
UniServer  Zero XII AMP Stack form Server running PHP 7.1.x
Joomla 3.6.5
#### Additional comments
Both 2.01 stable and 3.0.0 Beta Patchtester come up with the same issue. (URL Malformed).
Is there some PHP DLL extension I need to activate?  Don't know if it's my system, Github or something else.
![malformed_url_github_patchtest](https://cloud.githubusercontent.com/assets/17795632/21337764/12e6069c-c6ab-11e6-8e35-d3a70ff8bc99.PNG)

**Comment by roland-d** [comment]
@AMurray2016 I know this is an old issue but I am spring cleaning here :)

If your password contains the @ symbol that will break the Github URL we are trying to load. This is a known issue but Github is going to remove the username/password authentication in November of this year: https://developer.github.com/changes/2020-02-14-deprecating-password-auth/

So I will close this as the password option will be removed by Github.
