### ISSUE TITLE
Error  Uploaded package is not compatible with this Joomla! version.

### ISSUE THREAD

**Issue by brianteeman** [joomla-extensions/patchtester#184]
#### Steps to reproduce the issue
With the Joomla code nightly builds - as of  Monday, 30 January 2017 02:00:17 UTC

Try to install either the latest stable or the current beta release

#### Expected result
Component installs

#### Actual result
Error  Uploaded package is not compatible with this Joomla! version.

**Comment by mbabker** [comment]
There is not a string with that text in either the core Joomla language files nor the patch tester component...

**Comment by brianteeman** [comment]
Weird - Something added that string to my test site (not the nightly build I referenced as I was working on the wrong site)
