### ISSUE TITLE
PostgreSQL error

### ISSUE THREAD

**Issue by csthomas** [joomla-extensions/patchtester#185]
#### Steps to reproduce the issue
1. Install joomla on postgreSQL and com_patchtester 3 beta
2. Fetch data.
3. Search by pull ID.

#### Expected result
Found row or not without any errors.

#### Actual result
ERROR: operator does not exist: bigint ~~ unknown LINE 4: WHERE a.pull_id LIKE '%12313%' ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts. 

#### System information (as much as possible)
PHP 7.0.13-0ubuntu0.16.04.1
PostgreSQL 9.5.5

**Comment by mbabker** [comment]
Already fixed by https://github.com/joomla-extensions/patchtester/pull/176

If I remember I'll tag a new beta soon.  I've been putting it off because there's a stable blocking issue open but alas it seems it's going to be needed sooner than later.

**Comment by csthomas** [comment]
Thanks
