### ISSUE TITLE
[4.0] Patch Tester Settings not saved

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla-extensions/patchtester#188]
### Steps to reproduce the issue
Patch Tester > GitHub Authentication > Github Token: Insert Token and Save: Not saved and Error:
![bildschirmfoto 2017-03-19 um 13 22 00](https://cloud.githubusercontent.com/assets/8235763/24080838/0f969582-0ca7-11e7-9dda-262a3dc380d9.JPG)
### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by mbabker** [comment]
Closing per https://github.com/joomla/joomla-cms/issues/14769#issuecomment-287622108 - this is an error in com_config.
