### ISSUE TITLE
[beta 2] Table '#__patchtester_pulls' doesn't exist 

### ISSUE THREAD

**Issue by C-Lodder** [joomla-extensions/patchtester#190]
#### Steps to reproduce the issue

- Download and install beta 2 of the patch tester
- Attemt to go to the component in the backend

#### Actual result

> Table '#__patchtester_pulls' doesn't exist 

#### System information (as much as possible)

- Joomla [3.7] staging
- PHP 7.0.10

**Comment by mbabker** [comment]
While this crops up quite a bit, I have never been able to duplicate it.  All the stuff is defined correctly on this side, so the only possibility is there is some environment where the install library bugs out and doesn't run the install.sql file.

**Comment by C-Lodder** [comment]
I'll see if I can come up with a fix

**Comment by brianteeman** [comment]
https://github.com/joomla-extensions/patchtester/issues/186#issuecomment-301836142

**Comment by C-Lodder** [comment]
closing as duplicate
