### ISSUE TITLE
Add milestone label

### ISSUE THREAD

**Issue by 810** [joomla-extensions/patchtester#191]
#### Steps to reproduce the issue
Add milestone label on the pulls view, so users can check the correct version.

#### Expected result

Joomla 3.7.1  or Joomla 4.0.0

**Comment by zero-24** [comment]
Normally milestone are added after or with the commit. So basicly you can see that on the label. PR-xxx label. So maybe we can show that label? Even I'm not sure if that makes sense as patchtester is IIRC not the first point of contact for testing.

**Comment by mbabker** [comment]
Added processing where the labels are already being parsed to extract the branch based on the `PR-foo` labels and the ability to filter on that list.

**Comment by zero-24** [comment]
Thanks!
