### ISSUE TITLE
Fetch only Part of all PRs

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla-extensions/patchtester#195]
#### Steps to reproduce the issue
Similar #192, #194: Only a Part of all PRs are fetched (this Time first 50). Wanted to test https://github.com/joomla/joomla-cms/pull/12450, its not loaded.

Tried @mbabker 's [zip](https://github.com/joomla-extensions/patchtester/files/977231/com_patchtester.zip) with same Result as Patch Tester 3.0.0 Beta 2.
### System information
3.7.2-dev
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by Quy** [comment]
I manually made this change to fix this issue: https://github.com/joomla-extensions/patchtester/commit/66caae6668bcf80c47a3d2448638196b95f95467

**Comment by mbabker** [comment]
Closing, as noted the fix is included in master.

**Comment by franz-wohlkoenig** [comment]
Tried to install Master, got:
![bildschirmfoto 2017-05-21 um 12 53 08](https://cloud.githubusercontent.com/assets/8235763/26283246/75ea8bdc-3e24-11e7-92d5-d0801b91b29a.JPG)

**Comment by mbabker** [comment]
Because this repo isn't structured as an installable extension package.  You'll have to either download the repo files, manually place them into your CMS install, then discover install the extension; or install one of the last available packages then patch files as needed to get things working.

**Comment by franz-wohlkoenig** [comment]
thanks for info @mbabker

**Comment by franz-wohlkoenig** [comment]
tried 2nd Possibility (replaced Files from Master in Installation) but same Result: Patchtester fetch only first 3 Pages. So icannot Test older PRs.

**Comment by franz-wohlkoenig** [comment]
All fine, now works, thanks for Solution.
