### ISSUE TITLE
Link to Patchtester after Installation

### ISSUE THREAD

**Issue by ghost** [joomla-extensions/patchtester#199]
### Steps to reproduce the issue
Is it possible to get a Link to installed Patchtester in Message (and a Link to its "Options")?:
![bildschirmfoto 2017-06-01 um 12 08 40 kopie](https://cloud.githubusercontent.com/assets/8235763/26675257/8d8c65e2-46c3-11e7-94ab-34265b0f9a3c.jpg)

**Comment by zero-24** [comment]
I have read this issue now three time but i'm not sure what do you expect.

Do you want to extend the install message with a link? What link do you want on which text? Why do you want to link the marked text with the options? Or do you want fo extend this message and add some text plus a link?

**Comment by franz-wohlkoenig** [comment]
Feature Request is to click on Message (marked Text was a Suggestion) and Patchtester opened. A second Request is a second Link which open "Options" of Patchtester.

Reason: Now i have to open after Installation "Component", click on Patchtester, click on "Options".

**Comment by mbabker** [comment]
It's not much different than installing most other extensions.  Core by default doesn't have a mechanism for doing this so we'd have to use the postflight install task to add these extras.

**Comment by zero-24** [comment]
Isnt this just a language string we can change to add the two links as requested?

**Comment by mtmeyrick** [comment]
Have spent a short time trying to create something similar to what was requested. As @mbabker said its a postflight task which has created:
![image](https://user-images.githubusercontent.com/5739425/39048630-1991ba12-4496-11e8-8db6-bdc829acb398.png)

Is this the sort of thing you were looking for @franz-wohlkoenig??

**Comment by franz-wohlkoenig** [comment]
@mtmeyrick yes, exact what i was asking for.

**Comment by roland-d** [comment]
@mtmeyrick It has been a while since this was posted but spring cleaning is here. Do you still have the code change laying around and care to make a pull request?

**Comment by mtmeyrick** [comment]
I do still have the code mind haven't done a pull request for a while so will try and recap this and make a pull request for this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/patchtester/199">issues.joomla.org/tracker/patchtester/199</a>.</sub>

**Comment by roland-d** [comment]
Thank you @mtmeyrick

**Comment by richard67** [comment]
@roland-d Can this old issue be closed now as we have PR #264 almost ready?

**Comment by roland-d** [comment]
Yes, this can be closed as we have a pull request.
