### ISSUE TITLE
[4.0] Error at "Fetching GitHub Data"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla-extensions/patchtester#200]
#### Steps to reproduce the issue
Installed com_patchtester(beta3):
![bildschirmfoto 2017-06-25 um 16 52 41](https://user-images.githubusercontent.com/8235763/27517125-194e5dea-59c7-11e7-8326-4fbef1d3f04b.jpg)
### System information
4.0.0-dev
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by mbabker** [comment]
There are no uses of a `getTag()` method in this component.  So the error is something in core.  Turn on debug mode and a stack trace will be displayed.

**Comment by franz-wohlkoenig** [comment]
open an Issue on joomla/joomla-cms?

**Comment by mbabker** [comment]
Yes.
