### ISSUE TITLE
Error SQL Table 'joomla4.a1uo7_patchtester_pulls' doesn't exist

### ISSUE THREAD

**Issue by PhilETaylor** [joomla-extensions/patchtester#201]
#### Steps to reproduce the issue

try to install to Joomla 4 
Patch Tester 3.0.0 Beta 3

#### Expected result

installs

#### Actual result

```
JInstaller: :Install: Error SQL Table 'joomla4.a1uo7_patchtester_pulls' doesn't exist
JLIB_INSTALLER_ABORT_INSTALL_ABORTED
```

<img width="633" alt="image 2017-11-23 at 9 37 24 am" src="https://user-images.githubusercontent.com/400092/33166389-f4049022-d031-11e7-8510-4a5b43fcf42a.png">

#### System information (as much as possible)

http://screenshot.myjoom.la/0E2X030w2b45

**Comment by Quy** [comment]
Duplicate #186

**Comment by richard67** [comment]
@PhilETaylor Please test PR #221 .

**Comment by richard67** [comment]
@PhilETaylor Sorry, I just see yours is about J4. My PR is mainly helping with J3. You tested with Patchtester Beta 3, but meanwhile in Beta 4 there were some changes which solve that problem you had. Can you test again with Beta 4? If you then have the problem mentioned in Issue [#108 (comment)](https://github.com/joomla-extensions/patchtester/issues/186#issuecomment-473627667), then my PR #221 will help with that also for J4.

**Comment by roland-d** [comment]
@PhilETaylor Going to close this as this works for me with the current release.
