### ISSUE TITLE
Warning: preg_match() expects parameter 2 to be string

### ISSUE THREAD

**Issue by Quy** [joomla-extensions/patchtester#202]
#### Steps to reproduce the issue
Click `Fetch Data` button

#### Actual result
Warning: preg_match() expects parameter 2 to be string, array given in C:\xampp\htdocs\joomla-cms-4.0-dev\administrator\components\com_patchtester\PatchTester\Model\PullsModel.php on line 317
{"success":true,"message":"All data has been retrieved. Please close this modal window to refresh the page.","messages":null,"data":{"complete":true,"page":2,"lastPage":1,"header":"Successfully retrieved pull requests"}}

#### System information (as much as possible)
v4.0 alpha 2

**Comment by mbabker** [comment]
What patch tester version are you using?  3.0 beta 3 is first one with 4.0 compatibility.

**Comment by Quy** [comment]
beta 2. Updated to 3. All ok now. Thanks.
