### ISSUE TITLE
Error installing Beta3 on J4.0.0-alpha3

### ISSUE THREAD

**Issue by carlitorweb** [joomla-extensions/patchtester#205]
#### Steps to reproduce the issue
![screenshot_20180518160347](https://user-images.githubusercontent.com/3956472/40255335-d29b6cb8-5ab4-11e8-9897-571ac8d7fb25.png)

Any way of have working PatchTester on J4?

**Comment by franz-wohlkoenig** [comment]
Do you use https://github.com/joomla-extensions/patchtester/releases/tag/3.0.0-beta3?

If not, you should use this beta.

**Comment by carlitorweb** [comment]
I can swear I used that one!!!. Well, now work. Thank you @franz-wohlkoenig and sorry for this.
