### ISSUE TITLE
[4.0] Table hide "Apply Patch"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla-extensions/patchtester#207]
#### Steps to reproduce the issue
Using 3.0.0 Beta 3:

![screen shot 2018-07-16 at 11 46 15](https://user-images.githubusercontent.com/8235763/42752712-1215e586-88ef-11e8-9e2c-840b44b232f5.jpg)

Solution is to sort ascending and jump to last Page ... but if its possible to move Table on top?

**Comment by TobsBobs** [comment]
Hello @franz-wohlkoenig,

please see #206

**Comment by franz-wohlkoenig** [comment]
thanks @TobsBobs, haven't seen your Issue.

@mbabker In the Meantime joomla/joomla-cms#21006 is merged;-)

**Comment by mbabker** [comment]
And https://github.com/joomla-extensions/patchtester/commit/0f13b9893faf83f8b3bff565bd928b35e0704886 has been made already.

**Comment by franz-wohlkoenig** [comment]
That looks like i can close this issue, thanks @mbabker.

As i'm a User and get this after try to Install Master:

![screen shot 2018-07-16 at 14 28 30](https://user-images.githubusercontent.com/8235763/42758707-ae72fa12-8904-11e8-942d-dec795136a02.jpg)

i wait for next beta.

**Comment by mbabker** [comment]
This repo isn't set up in a way where you can just download it and install a package, an extension package has to be built using the scripts for Joomla to take it.  Otherwise for now you can just download the Atum template overrides and upload those until I create a new release package.

**Comment by franz-wohlkoenig** [comment]
thanks michael for Comment.
