### ISSUE TITLE
[4.0] Overlay at "Fetch Data" should be below Modale

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla-extensions/patchtester#208]
#### Steps to reproduce the issue
As Title say:
![screen shot 2018-07-17 at 05 39 37](https://user-images.githubusercontent.com/8235763/42797247-a4597756-898e-11e8-8e6d-5bf901958159.jpg)

### System information
- Nightly Build 4.0.0-alpha4-dev
- Multilingual Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by mbabker** [comment]
IIRC it's a template issue, not something I can fix at the component level.  // @dgrammatiko

**Comment by franz-wohlkoenig** [comment]
should i open an Issue at joomla/joomla-cms?

**Comment by franz-wohlkoenig** [comment]
closed as having Pull Request [#21343](https://github.com/joomla/joomla-cms/issues/19408)
