### ISSUE TITLE
[Feature Request] Fetch only Target Branch

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla-extensions/patchtester#210]
#### Steps to reproduce the issue
Patchtester fetch all Branches independend of installed Joomla-Version (3.8 get also 4.0-Patches). If possible load only Branch needed.

**Comment by alikon** [comment]
can  you test #211

**Comment by franz-wohlkoenig** [comment]
thanks, will do. How can i install this PR #211?

**Comment by franz-wohlkoenig** [comment]
closed as having Pull Request #211
