### ISSUE TITLE
Credential-based login with "#" in credentials breaks Github connection

### ISSUE THREAD

**Issue by SniperSister** [joomla-extensions/patchtester#214]
#### Steps to reproduce the issue
Try to setup the credential based login, configure your Github account to use a password with a "#" somewhere in the string. Fetch the list of issues.

#### Expected result
Issuelist is being fetched.

#### Actual result
You'll get a connection error.

#### Additional comments
Add the first glance it looks like the issue is being caused by the lack of encoding for the # character while setting up the connection:
https://github.com/joomla-extensions/patchtester/blob/master/administrator/components/com_patchtester/PatchTester/GitHub/GitHub.php#L88

This leads to a URL like this being used for the connection:
> user:pass#word@github.com

The url gets truncated after the #, because that's used for html anchors.

A simple 
> $password = str_replace('#', '%23', $password);

Should fix it, for both, username and password

**Comment by mbabker** [comment]
Fixed by #215
