### ISSUE TITLE
[4.0] Language change for the last column of patch tester

### ISSUE THREAD

**Issue by hardik-codes** [joomla-extensions/patchtester#217]
#### Steps to reproduce the issue
Open the Joomla! Patchtester

* The right most column ```Test This Patch``` in my humble opinion should be ```Apply/Revert Patch``` as the user is able to apply or revert the patch there. The testing part is to be done by the user itself manually and not done by the ```Apply Patch``` button

![tester](https://user-images.githubusercontent.com/34353697/54920603-9e52f100-4f29-11e9-9195-09172a151612.jpg)

* Also the column for ```Github``` should be changed to ```Github Link``` as the latter is more informative

The above is just my opinion, I request members to comment on this.

**Comment by hardik-codes** [comment]
@mbabker @wilsonge @jeckodevelopment

**Comment by jeckodevelopment** [comment]
> The right most column Test This Patch in my humble opinion should be Apply/Revert Patch as the user is able to apply or revert the patch there. The testing part is to be done by the user itself manually and not done by the Apply Patch button

Given that the button text is "Apply Patch", I think that having `Apply/Revert Patch` as column title would work.

>    Also the column for Github should be changed to Github Link as the latter is more informative

In this case, I'd stay with `GitHub` also because the other colum is Issue Tracker (without link) and is fine.

**Comment by hardik-codes** [comment]
@jeckodevelopment should I do a PR for the same

**Comment by alikon** [comment]
The change happens in the button wich is Apply when the pr is not yey applyied and Revert when the pr ha been applyed...  so imho it's quite clear

**Comment by hardik-codes** [comment]
> The change happens in the button wich is Apply when the pr is not yey applyied and Revert when the pr has been applyed... so imho it's quite clear

@alikon but the the last column name is not suggestive of what the buttons do over there. ```Test This Patch``` does not clearly define the column there

**Comment by alikon** [comment]
feel free to submit a pr i'm only expressing my POV

**Comment by mbabker** [comment]
To be honest, I don't like the "Apply/Revert Patch" label any better than I do the current one.

And if I'm also being totally honest, I don't like how the GitHub and Issue Tracker column headers are essentially the same text as the cells they label just with different markup structure (and yes, this is me saying the "J! Issue" button text should change).  I'm also fairly sure having these marked up in a way that looks like buttons fails accessibility (they're links and should look like such), but that's now derailing this issue.

**Comment by hardik-codes** [comment]
@mbabker instead of ```Apply\Revert Patch``` can we go with any other label

**Comment by mbabker** [comment]
In all honesty I don't really care, just looking at things right now I can say I don't really like either the current label or the proposed "Apply/Revert Patch" label.

**Comment by hardik-codes** [comment]
In that case I think we should leave the things as they are

**Comment by mbabker** [comment]
If someone's got an idea, please feel free to submit it.  I'm just providing my feedback here, and right now personally I just feel like both labels are "m'eh", they aren't great but they aren't terrible.

**Comment by roland-d** [comment]
The Github and Issue tracker columns have been removed by now and as for the labels I agree with Michael here.

Closing this as things can be left as they are.
