### ISSUE TITLE
Problem with Patch Tester in Joomla 4

### ISSUE THREAD

**Issue by sandewt** [joomla-extensions/patchtester#224]
#### Steps to reproduce the issue

When setting up a local development environment to test bugs for Joomla 4.x *, I get the an error message after installing the patch tester: 

Goto: Control Panel > Components > Joomla! Patch Tester

#### Expected result

Joomla! Patch Tester works proberly.

#### Actual result

Error message:

An error has occurred.
0 Class '\ PatchTester \ Controller \ DisplayController' not found.

#### System information

Systeem: Windows 10 - XAMPP - Joomla! 4.0.0-alpha11-dev - PHP 7.3.7

#### Additional comments

\* The same setup / method for Joomla 3.x runs without problems.

Note: Composer is not installed in the test environment.

**Comment by sandewt** [comment]
ISSUE CAN BE CLOSED:

Oops, I used an older version, **Patch Tester 3.0.0 Beta 4 **works fine.

**Comment by richard67** [comment]
@sandewt You can close own issues yourself. There should be a button for that at the bottom of your own issues in GitHub.

**Comment by sandewt** [comment]
> ISSUE CAN BE CLOSED:

@richard67, thanks

I've seen it,
