### ISSUE TITLE
Non-Platform Portable Code

### ISSUE THREAD

**Issue by mbabker** [joomla-extensions/patchtester#233]
https://github.com/joomla-extensions/patchtester/blob/0a1792da5812db8a5576757f3ae5f18b95f96df1/administrator/components/com_patchtester/PatchTester/Model/PullModel.php#L221

There is a HTTP API in Joomla for a reason.  Perhaps using it would be good here.

https://github.com/joomla-extensions/patchtester/blob/0a1792da5812db8a5576757f3ae5f18b95f96df1/administrator/components/com_patchtester/PatchTester/Model/PullModel.php#L230

You've now pretty much forced anyone using your vision of this component to turn on URL support for file streams.  Well minded administrators disable this functionality.

**Comment by richard67** [comment]
@mbabker You mean do it like here: [https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_joomlaupdate/Model/UpdateModel.php#L397](https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_joomlaupdate/Model/UpdateModel.php#L397), i.e. use `HttpFactory::getHttp()`?

**Comment by richard67** [comment]
@mbabker Maybe like that: #249 ?

**Comment by richard67** [comment]
Please test #249 ;-)

**Comment by roland-d** [comment]
This has now been refactored to use the Joomla API.
