### ISSUE TITLE
JavaScript Changes For The Sake Of Change

### ISSUE THREAD

**Issue by mbabker** [joomla-extensions/patchtester#236]
The `patchtester.js` file was changed for the sake of changing it, I can't deduce any other valid explanation for why it was changed.  It also removed a very explicit warning message when using the reset function.

This is why there should be a reason for change and not just "oh this is the flavor of the day well cool beans".  Not to mention code reviews, because anyone would've seen that removal if they had looked for more than half a second.

**Comment by roland-d** [comment]
Good call. I have restored the warning message.
