### ISSUE TITLE
Unexplained removal of script.php

### ISSUE THREAD

**Issue by mbabker** [joomla-extensions/patchtester#237]
The `script.php` file is used to block installation on unsupported Joomla and PHP versions, and handled template overrides back in the day when the component was well written to support multiple versions of Joomla.  Inexplicably this file was removed and there are no safeguards present from installing the hacky 4.0 version of the component on a 3.x site.

**Comment by mbabker** [comment]
Not to mention, as is standard for all Joomla extensions using an install script, is the standardized mechanism for ensuring outdated files get removed from a site when updating the extension.  Seems kind of sloppy to not be able to support an in-place upgrade.

**Comment by roland-d** [comment]
Agree, we should keep the `script.php`. This file has now been restored.
