### ISSUE TITLE
Fix Git Branching Model

### ISSUE THREAD

**Issue by mbabker** [joomla-extensions/patchtester#239]
Joomla has a bad habit of branching new versions instead of keeping master as the newest development version.  You should not have a 4.0-dev branch (neither should the CMS, and the Framework repos shouldn't have 2.0-dev branches either).  Follow the lead of a well established project like Symfony or Laravel or WordPress or Drupal and adjust branching so that the 3.x release of this component is a branch and master is your current 4.0 code.  Or, Joomla just keeps inventing its own standards because screw industry norms.

**Comment by roland-d** [comment]
Hey Michael,
I agree with you that we should use the git branching model. Looking at Symfony, Laravel, and WordPress they work in a different way I am used to. I am used to the Git Flow principle but that is not how Github Flow works.

Git flow I mean is this one: https://nvie.com/posts/a-successful-git-branching-model/

The branching model has now been updated.
