### ISSUE TITLE
PatchTester alert window and filter missing left margin

### ISSUE THREAD

**Issue by vlaucht** [joomla-extensions/patchtester#244]
#### Steps to reproduce the issue

1. Install latest Patch Tester
2. go to Components --> Joomla! Patch Tester

#### Expected result

alert window and filter should have a left margin

#### Actual result

![PatchTesterBug](https://user-images.githubusercontent.com/54251018/67618910-94fa7180-f7f5-11e9-999f-53e3a1c1dfe9.PNG)

#### Additional comments
I will fix this issue and file a PR

**Comment by vlaucht** [comment]
I have fixed this and also fixed the search button.

![PatchTesterBugFixed](https://user-images.githubusercontent.com/54251018/67620145-c4b07600-f803-11e9-8ed6-455ebc860bef.PNG)

**Comment by mbabker** [comment]
The screenshot here looks like you tried installing the 4.0 version on Joomla 3.x.  The 4.0 version is sadly not compatible with 3.x, so you should check the 3.0 version of patchtester first.

**Comment by vlaucht** [comment]
Ah I see. I've installed Joomla 4.0 and PatchTester 4 and you're right. Everything looks fine.
