### ISSUE TITLE
Missing Language Srtring «COM_PATCHTESTER_HEADING_FETCH_DATA»

### ISSUE THREAD

**Issue by blueforce** [joomla-extensions/patchtester#254]
#### Steps to reproduce the issue
1. Go to fetch Data
2. Popup appears
3. See the title of the popup

#### Expected result
Title is Translated

#### Actual result
<img width="1190" alt="Bildschirmfoto 2020-02-05 um 13 55 37" src="https://user-images.githubusercontent.com/1141234/73844076-211e2b00-4820-11ea-95f7-8b88973ef36e.png">

**Comment by roland-d** [comment]
@blueforce Thank you for the report, I have now fixed this for the next release.
