### ISSUE TITLE
[RFC] What shall Patchtester do with the libraries/autoload_psr4.php file on Joomla 4?

### ISSUE THREAD

**Issue by richard67** [joomla-extensions/patchtester#257]
When having a Pull Request (PR) for version 4 of the CMS which renames classes or moves around class files, we have to delete file `libraries/autoload_psr4.php` in such cases.

Question: What shall the Patchtester do when applying and reverting such PR's?

Currently, when I search for "autoload_psr4" in the sources on the master branch, I find nothing.

Should there be some handling for that file added to the Patchtester?

Maybe just delete that file in any case when doing apply or revert on J4? That would work and we would be on the safe side and it would be easy. But maybe something speaks against that?

**Comment by richard67** [comment]
@wilsonge What do you think about the above questions?

**Comment by wilsonge** [comment]
I’d delete it every time a patch is applied or reverted

**Comment by richard67** [comment]
@wilsonge Thanks for feedback.

@roland-d Will check if I can make a PR here for that.

Further feedback is welcome. But I think George is right. Everything else than just deleting it, i.e. trying to find out if it has to be deleted or not, would be a complicated thing and a waste of time for nothing.

**Comment by richard67** [comment]
Closing as having PR #258 . Please test. I have to test it now, too.
