### ISSUE TITLE
Apply results in broken composer dependencies when applying a PR which changes them

### ISSUE THREAD

**Issue by richard67** [joomla-extensions/patchtester#259]
#### Steps to reproduce the issue

On a patchtester based on current master branch, i.e. including all corrections merged since the last 4.0 beta, apply PR [https://github.com/joomla/joomla-cms/pull/25117](https://github.com/joomla/joomla-cms/pull/25117).

This is a PR which changes composer.json and composer-lock.json.

#### Expected result

Either patch applied, or some error message that it isn't allowed for this or that reason.

#### Actual result

Backend and frontend are white pages immediately after having clicked "apply", or in my last test the patchtester has shown the patch applied, but when navigating to somewhere else in backend it was blank page.

In PHP error log:

```
PHP Warning:  require(/home/richard/lamp/public_html/joomla-cms-4.0-dev/libraries/vendor/composer/../zendframework/zend-diactoros/src/functions/create_uploaded_file.php): failed to open stream: No such file or directory in /home/richard/lamp/public_html/joomla-cms-4.0-dev/libraries/vendor/composer/autoload_real.php on line 66, referer: https://www.joomla-40-dev.vmkubu02.vmnet2.local/administrator/index.php?option=com_patchtester&view=pulls
PHP Fatal error:  require(): Failed opening required '/home/richard/lamp/public_html/joomla-cms-4.0-dev/libraries/vendor/composer/../zendframework/zend-diactoros/src/functions/create_uploaded_file.php' (include_path='.:/usr/share/php') in /home/richard/lamp/public_html/joomla-cms-4.0-dev/libraries/vendor/composer/autoload_real.php on line 66, referer: https://www.joomla-40-dev.vmkubu02.vmnet2.local/administrator/index.php?option=com_patchtester&view=pulls
```

Running `composer install` and `npm ci` or removing the `libraries/autoload_psr4.php` file or all of that in combination doesn't fix it.

#### System information (as much as possible)

PHP 7.3 on Linux.

#### Additional comments

It could be that there is some systematic error when having PR's which change composer dependencies.

**Comment by roland-d** [comment]
@richard67 This should now be fixed in the `master` branch.

**Comment by richard67** [comment]
Confirmed, solved with recent commits. Just have tested with a package I'be build a few minutes ago. Now for the patch mentioned in my descriptions, I get:
![patchtester-4-alert-when-patch-dangerous](https://user-images.githubusercontent.com/7413183/78402207-78f7c900-75fa-11ea-96e3-6f9da370cec4.png)

And the patch is not applied.

After that, applying and reverting other patches works as well as before trying to apply the critical patch.

So this issue here is solved.
