### ISSUE TITLE
Patch tester on J4  with J4 patch test fails to add a patch, to test

### ISSUE THREAD

**Issue by softforge** [joomla-extensions/patchtester#262]
### Steps to reproduce the issue

Went to apply patch (27601) to do the second test as Nicola had just successfully applied patch and tested successfully. 
But for me the patch failed to apply with the message 
Error
The patch could not be applied because it would break the site. Check the pull request to see if it is up to date

I had just fetched all as had Nicola so for him the patch applied (I was watching his screen in the PBF without P)
I went to do second test when this happened

### Expected result
Patch installs

### Actual result
Patch failed with 
Error
The patch could not be applied because it would break the site. Check the pull request to see if it is up to date![screen shot 2020-04-04 at 10 27 52](https://issues.joomla.org/uploads/1/68efaf0b4017db5dcf38a127402204a0.png)

### System information (as much as possible)
Install the latest nightly 
Joomla_4.0.0-beta1-dev-Development-Full_Package.zip
Add the J4 patch tester 
Patch Tester 4.0.0 Release Candidate
GitHub Repo set to Joomla!CMS
Github Auth Method Token
PHP Version	7.3.16
Web Server	Apache
WebServer to PHP Interface	fpm-fcgi
10.1.44-MariaDB

### Additional comments
![Annotation 2020-04-04 111731](https://user-images.githubusercontent.com/1078933/78424860-1806da00-7668-11ea-8a11-958a44fc17ae.png)

**Comment by richard67** [comment]
Webserver OS is Windows? Or Linux?

**Comment by alikon** [comment]
it is windows 10

**Comment by richard67** [comment]
Seems to be a Windows path separator thing, that's why I've asked. I think we are close to a fix.

**Comment by richard67** [comment]
Unfortunately I have Linux only here for testing.

**Comment by roland-d** [comment]
I am working on a fix

**Comment by roland-d** [comment]
Please test the Patch Tester 4.0.0 RC2:
https://github.com/joomla-extensions/patchtester/releases/tag/4.0.0-rc2

You will need to do the following:
1. Install the package
2. Go to the Patch Tester
3. Click on the Options tab
4. Click on the tab `CI Server Settings`
5. Set `Switch CI Integration` to `No`
6. Save & Close

Alternative solution is to uninstall the Patch Tester and then install the Release Candidate 2 version. Now you will have to enter your credentials again.

**Comment by roland-d** [comment]
@alikon See up here ^^

**Comment by roland-d** [comment]
@alikon I am going to continue the discussion in the issue rather than the commit because the discussion it not related to the commit.

> this error is not clear

You are welcome to propose a PR with better wording.

> what I should do when it happens ?

What you should do is to check the PR, if it has any problems. There are no fixed steps for this.

> simply turn off CI server ?

You can do that but testing a patch from Github you cannot test CSS/JS changes. So you can still not test the patch if it contains CSS/JS changes. The error is stating exactly what would happen. If the patch would have been applied, your site will have been broken.

> again not too much clear in humbly opinion

Let's clarify it then.

**Comment by alikon** [comment]
> What you should do is to check the PR, if it has any problems. There are no fixed steps for this.

a normal jhon@doe user simply cannot do this nor is expected to do it nor to understand it deeply
cause it is a normal end-user not a developer

that's what i'm trying to say

**Comment by roland-d** [comment]
What is your suggestion for a John Doe user to do in this case?

**Comment by alikon** [comment]
1 million dollar question
i don't have a perfect answer/solution to this 
maybe a fully explanation on docs,jooma,org / FAQ pages

**Comment by softforge** [comment]
Thank you for working on this so quickly Roland-d
