### ISSUE TITLE
[J4] - Missing language string "COM_PATCHTESTER_XML_DESCRIPTION"

### ISSUE THREAD

**Issue by conconnl** [joomla-extensions/patchtester#263]
![modified](https://user-images.githubusercontent.com/11913918/78451010-07b02880-7683-11ea-9752-8e2c59043254.png)

**Comment by mtmeyrick** [comment]
Believe this has been the case in most if not all previous versions to be honest

**Comment by conconnl** [comment]
Issue was created on request of Roland.

**Comment by richard67** [comment]
@roland-d So the missing string is defined, but only in the `com_patchtester.sys.ini` language files, not in the `com_patchtester.ini` (without `.sys`) files. So 2 ways to go: Add the strings in the `.sys`files to the files without `.sys`, or always load the `com_patchtester.sys.ini`, too.

Let me know what you prefer or what's the right way.

I would prefer to add the 3 language strings in the `.sys.ini` to the `.ini` files, and that's it.

**Comment by richard67** [comment]
@roland-d Ha, even better now: I see it is solved with PR #268 ;-)

**Comment by richard67** [comment]
No, wait, it's the extensions update view I have to check.

**Comment by richard67** [comment]
No, it's not solved with #268 .

**Comment by richard67** [comment]
@roland-d @conconnl Am working on the solution. Stay tuned.

**Comment by richard67** [comment]
@conconnl I've added the fix to my PR #268 . Please test. You can find a link to a patched patchtester package in that PR.

**Comment by roland-d** [comment]
Fixed with PR #268
