### ISSUE TITLE
Options Credentials are not working in GitHub Authentication

### ISSUE THREAD

**Issue by astridx** [joomla-extensions/patchtester#267]
#### Steps to reproduce the issue

1. Install Patch tester and use Credentials in the options for GitHub Authentication
![Joomla  Patch Tester Settings   test   Administration](https://user-images.githubusercontent.com/9974686/78828030-5abc0f80-79e4-11ea-82b3-9d66a37cc8e1.png)

2. Try to fetch patches and see, that this is not working. (Fetch patches via GitHub Authentication set to Token is working)

3. Try to apply a patch with GitHub Authentication set to Credentials. It is not possible to do this. You see an error containing your password. (Apply patches via GitHub Authentication set to Token is working)
![Joomla  Patch Tester   test   Administration](https://user-images.githubusercontent.com/9974686/78828032-5b54a600-79e4-11ea-844a-807a6840ba93.png)

**Comment by roland-d** [comment]
Hello @astridx Does your password have a @ in it? That would be a known issue and later this year the username/password will be removed from the Patch Tester because GitHub is going to remove that as well.

So the advice is to always use the token.

**Comment by astridx** [comment]
Thank you Roland.

I use the token. So for me it is OK.

I only want to tell you, that there is (maybe) a problem with the credentials method.  

No, there is no @ in my password.

**Comment by roland-d** [comment]
@astridx There are some known issues with the password credentials, especially if you have special characters in them. The code tend to choke on it :)

Thank you for reporting this, since GitHub is going to pull the plug on passwords I won't be fixing this.
