### ISSUE TITLE
Inconsistent default CI setting

### ISSUE THREAD

**Issue by SharkyKZ** [joomla-extensions/patchtester#279]
#### Steps to reproduce the issue

Install Patchtester.
View its configuration. Notice that `CI Integration` option appears to be off.
Fetch and apply a pull request.

#### Expected result

Pull request applied without using CI.

#### Actual result

Pull request applied using CI.

#### System information (as much as possible)

Irrelevant.

#### Additional comments

It's an easy fix but I don't know whether CI should on or off by default.

**Comment by roland-d** [comment]
Hello @SharkyKZ 

The CI setting was On by default. When I took over the Patch Tester I found out that the CI server is broken and as such you cannot apply anything. So I now set it to Off by default until the CI server is fixed. In case you have an old version installed and install the new one over it, it will keep the old settings, so you have to manually turn it off.

Once the CI server is up and running as it should, I will turn it on again. Annoying but this is the best I can do at this point. The advantage of the CI server is that it has the NPM resources compiled. That is why we have the CI server.

Do you know why it is pulling it from the CI server?

**Comment by SharkyKZ** [comment]
CI option defaults to enabled in code here:

https://github.com/joomla-extensions/patchtester/blob/841af8aa2070d88c855decffca2eb25e07e850d4/administrator/components/com_patchtester/PatchTester/Model/PullModel.php#L92

https://github.com/joomla-extensions/patchtester/blob/841af8aa2070d88c855decffca2eb25e07e850d4/administrator/components/com_patchtester/PatchTester/Model/PullModel.php#L782

If Patch Tester doesn't add its params when installing, the default value in code and in `config.xml` should match.

**Comment by roland-d** [comment]
I have updated the code. Thank you for that.
