### ISSUE TITLE
Add a limit on the number of items retrieved

### ISSUE THREAD

**Issue by roland-d** [joomla-extensions/patchtester#28]
It would be good to have a limit on the number of items retrieved from Github. We could have a kind of filter to get the last x items or only get the PR ID that is set in the search box or only for a given time limit. Just some ideas from the top of my head.

**Comment by mbabker** [comment]
Given the refactored fetch, I don't think this is so practical to accomplish right now.  The fetch still pulls everything but it's not as error prone.  Since the pulls are stored to the database now, the regular filters can handle the rest.
