### ISSUE TITLE
Joomla 4 not showing error message when patch applied and attempting to fetch

### ISSUE THREAD

**Issue by PhilETaylor** [joomla-extensions/patchtester#284]
#### Steps to reproduce the issue
Patch Tester 4.0.0 Release Candidate 2
Install a patch
Click fetch

#### Expected result

Error message to tell me something 

#### Actual result

Nothing appears to happen - left at this screen:

<img width="887" alt="Screenshot 2020-06-09 at 21 09 23" src="https://user-images.githubusercontent.com/400092/84194815-810a3400-aa95-11ea-860e-ae157c86d5de.png">

 the Ajax response contains an error not displayed to the user

```json
{"success":false,"message":"Cannot fetch data from GitHub while there are applied patches. Please revert those patches before continuing.","messages":null,"data":null}
```

**Comment by particthistle** [comment]
Based on the workaround that's been provided to me, the fetch data process could avoid this error occurring by checking the number of records in #_patchtester_tests first. It would then trigger an alert if the record count is >0, as that's where the data is stored for the applied patches.

If you wanted to improve the UX there you could look at:
- display an alert message "Please revert patches that are currently applied before fetching fresh Github Data"
- filters the patch list to the list of applied patches so the user can revert patches immediately.

**Comment by roland-d** [comment]
This has been fixed in the upcoming release, to show the message in the modal.
