### ISSUE TITLE
[4.0.0 RC3] Description of "GitHub Account Password" is shown twice

### ISSUE THREAD

**Issue by ghost** [joomla-extensions/patchtester#293]
#### Steps to reproduce the issue
- Open ```option=com_config&view=component&component=com_patchtester```
- Open Tab "GitHub Authentication"
- Select " GitHub Authentication Method: Credentials"
- Description of "GitHub Account Password" is shown twice:
![Screen Shot 2020-08-31 at 07 23 50](https://user-images.githubusercontent.com/70466955/91685559-fc422a00-eb5a-11ea-8820-3be95d608a5b.png)

#### Expected result
Description is shown below Value-Field.

#### Actual result
Description is shown above and below Value-Field.

#### System information (as much as possible)
Patch Tester 4.0.0 Release Candidate 3
php: Linux lamp112.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.7.el6h.x86_64 #1 SMP Mon Dec 17 12:02:35 EST 2018 x86_64
dbserver: mysql
dbversion: 5.7.30-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.3.19
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

#### Additional comments

none

**Comment by roland-d** [comment]
Thank you for the report but this is a Joomla core issue. When you set a field as password in the global configuration, it renders the password description twice.

**Comment by gostn** [comment]
havent set a password, using a token.
