### ISSUE TITLE
[4.0.0 RC3] Show Warning once

### ISSUE THREAD

**Issue by ghost** [joomla-extensions/patchtester#294]
#### Steps to reproduce the issue
Alert "Warning" is shown every Pageload:
![Screenshot_2020-09-05 Joomla Patch Tester - fw4 - Administration](https://user-images.githubusercontent.com/70466955/92299170-4444c080-ef50-11ea-920c-81e45259d89d.png)

#### Expected result
Warning is shown only on first Patchtesterload ~~or like "System - Joomla! Statistics"~~.

#### Actual result
Alert "Warning" is shown every Pageload.

#### System information (as much as possible)
php: Linux lamp131.cloudaccess.net 3.10.0-714.10.2.lve1.5.17.el6h.x86_64 #1 SMP Mon Apr 30 13:48:47 EDT 2018 x86_64
dbserver: mysql
dbversion: 5.7.24-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: false
phpversion: 7.3.21
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

**Comment by roland-d** [comment]
This won't be changed, see issue #235 This is a pre-stable release so it is good to show the message. Once things are stable, the message will be gone.
