### ISSUE TITLE
COM_PATCHTESTER_FETCH_AN_ERROR_HAS_OCCURRED

### ISSUE THREAD

**Issue by Quy** [joomla-extensions/patchtester#295]
#### Steps to reproduce the issue

![error](https://user-images.githubusercontent.com/368084/92758894-0971cc80-f344-11ea-97cc-26df5d50896c.png)

**Comment by Formatio-hippocampi** [comment]
confirmed

**Comment by roland-d** [comment]
Thank you, the string is now translated.
