### ISSUE TITLE
[4.0.0 RC3] "Number to Display" use always default list limit of "Global Configuration"

### ISSUE THREAD

**Issue by ghost** [joomla-extensions/patchtester#296]
#### Steps to reproduce the issue
- Change "Number to Display" to a different limit than in "Global Configuration"
- "Number to Display" switch back to "Global Configuration"-Setting
![Screen Shot 2020-09-12 at 08 32 34](https://user-images.githubusercontent.com/70466955/92989310-a878fe80-f4d3-11ea-8e24-d478050ad3e4.png)

#### Expected result
Change "Number to Display" is saved. 

#### Actual result
Change "Number to Display" isn't saved. 

#### System information (as much as possible)
php: Linux lamp131.cloudaccess.net 3.10.0-714.10.2.lve1.5.17.el6h.x86_64 #1 SMP Mon Apr 30 13:48:47 EDT 2018 x86_64
dbserver: mysql
dbversion: 5.7.24-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: false
phpversion: 7.3.21
server: Apache
sapi_name: cgi-fcgi
version: Nightly Build - Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

**Comment by roland-d** [comment]
Thank you for the report. This has been fixed for the next release.
