### ISSUE TITLE
[4.0] COM_PATCHTESTER_FETCH_AN_ERROR_HAS_OCCURRED on fetch data

### ISSUE THREAD

**Issue by hans2103** [joomla-extensions/patchtester#297]
#### Steps to reproduce the issue

- Install Joomla 4.0
- Adjust _Options_ 
  - _GitHub Authentication_ => make sure you have your _GitHub Authentication Method_ filled
  - _GitHub Repository_ => 
    - _GitHub Repository_ = Custom
    - _Custom Project Owner_ = `joomla`
    - _Custom Project Repository_ = `cassiopeia`
- _Save & Close_
- _Fetch Data  - 

#### Expected result

No error 

#### Actual result

A modal appears with the following error message:
```
COM_PATCHTESTER_FETCH_AN_ERROR_HAS_OCCURRED

Notice: Undefined offset: 0 in /Users/hans2103/Sites/joomla4/public_html/libraries/vendor/joomla/database/src/DatabaseQuery.php on line 464
{"success":false,"message":"Column count doesn't match value count at row 1","messages":null,"data":null}
```

I think it is a false positive, since the actual data has been fatched.

**Comment by roland-d** [comment]
@hans2103 Thank you for the report. It was not a false-positive. The issue is that this repo doesn't have any labels, that was triggering the notice.
