### ISSUE TITLE
Invalid issue tracker link sometimes

### ISSUE THREAD

**Issue by N6REJ** [joomla-extensions/patchtester#298]
#### Steps to reproduce the issue
If you use a custom repository the issue tracker doesn't link to the given repo but instead links to the joomla-cms repo.
the "github" link is fine but the "issue tracker" one is wrong.

#### Expected result
clicking on issue tracker brings up proper issue/pr.

#### Actual result
brings up joomla-cms issue of same #
![image](https://user-images.githubusercontent.com/1850089/95238201-c7b33500-07ce-11eb-840e-b4963f576bb8.png)
( note the double // ) also

#### System information (as much as possible)

options:
![image](https://user-images.githubusercontent.com/1850089/95238017-8b7fd480-07ce-11eb-8514-dbe879a839ae.png)
J! 4.0 using cassiopeia development branch.

**Comment by zero-24** [comment]
> If you use a custom repository the issue tracker doesn't link to the given repo but instead links to the joomla-cms repo.
the "github" link is fine but the "issue tracker" one is wrong.

Yes as there is no issue tracker (issues.joomla.org) for cassiopeia. So we might just remove that button in that cases @roland-d ?

**Comment by roland-d** [comment]
That is a valid point @zero-24 Agree, we should only show the link when the repo is set to the Joomla repo. Going to fix that.

**Comment by roland-d** [comment]
Thank you for reporting this, I have now changed this behavior for the next release.
