### ISSUE TITLE
Open tester options: method token

### ISSUE THREAD

**Issue by gostn** [joomla-extensions/patchtester#299]
#### Steps to reproduce the issue
1. After installation click on ´Go to the Joomla Patch Tester Options´

![image](https://user-images.githubusercontent.com/71960554/95298769-e2dc7e00-087c-11eb-92c1-8401e8b5c516.png)

2. Method ´None`is selected

![Screen Shot 2020-10-07 at 09 01 54](https://user-images.githubusercontent.com/71960554/95298834-fdaef280-087c-11eb-9488-ee4ffd3bc642.png)

3. Feature Request: Method token is selected

![Screen Shot 2020-10-07 at 09 02 07](https://user-images.githubusercontent.com/71960554/95298982-36e76280-087d-11eb-86ad-621805fbb23d.png)

#### Additional comments
GitHub will discontinue the use of username and password on of November 13, 2020 at 4:00 PM UTC.

**Comment by zero-24** [comment]
Yes this is something that has been fixed in the upstream github framework package. Once @roland-d updates that this issue should be fixed.

**Comment by roland-d** [comment]
@zero-24 Not sure what you mean here. The user is requesting to change the default value to token. I agree that will be better as we recommend that option. This has now been changed for the next release.

**Comment by zero-24** [comment]
Ah seems i have missed that. My comment was about that the token in the URL is no longer supported by github but that is fixed by the latest joomla-framework/github-api release.
