### ISSUE TITLE
4.0.0.: ´Filter Label´ miss style

### ISSUE THREAD

**Issue by gostn** [joomla-extensions/patchtester#304]
#### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/71960554/96213202-b6112080-0f78-11eb-9beb-b0baf585de92.png)

#### Expected result

Same style as other filter.

#### Actual result
missing style.

#### System information (as much as possible)
![image](https://user-images.githubusercontent.com/71960554/96213123-85c98200-0f78-11eb-924d-29d668217bf8.png)

#### Additional comments

Filter works

**Comment by richard67** [comment]
@gostn Have you noticed that the label filter is a multi-select, i.e. you can select more than one label with use of the "ctrl" key while selecting the labels?

Sure the style could be nicer, but it doesn't need to be the same as for the single-selects.

It's more comfortable to have it bigger, in my opinion.

But you are right, it doesn't look  nice.

**Comment by gostn** [comment]
> Have you noticed that the label filter is a multi-select

no, havent this idea. thanks for hint.

**Comment by richard67** [comment]
@brianteeman Do you have an idea how we could pimp this multi-select for the labels?

Not sure if a fancy select like we have it in backend e.g. for selecting tags for articles would be the best choice, but it could be one.

But at least we should have a different look for the "Filter Label" text, which is not a selectable option but the label of that select, and the selectable options (i.e. the PR labels).

**Comment by brianteeman** [comment]
take a look at the tag filter in core views

**Comment by richard67** [comment]
Ah, the list views in backend. Silly me.

**Comment by richard67** [comment]
Hmm, those filters where you have to start to type something suitable before you can see anything ... I never was happy with them.

I leave it up to @roland-d to decide if those should be used for the PatchTester, too.

**Comment by roland-d** [comment]
I did mention this issue in Glip, using the core style requires a complete rewrite of the view, that is going to need more time than I have available at this point. So I took this approach to have something that works but to some not look so pretty rather than have nothing at all.

In short, I will convert this to core style.

**Comment by gostn** [comment]
> you can select more than one label with use of the "ctrl" key while selecting the labels

for mac-users: use ´cmd´

**Comment by gostn** [comment]
a solution like github:

![Screen Shot 2020-10-17 at 10 31 47](https://user-images.githubusercontent.com/71960554/96332420-247edd00-1064-11eb-9dbc-6ad8c7936557.png)

**Comment by ceford** [comment]
I though this was a bug and did not realise it was a multi-select until I cam here. For me it would be prettier if it were the last filter item, after Filter Target Branch. When it wraps there is a big space down to the last filter item.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/patchtester/304">issues.joomla.org/tracker/patchtester/304</a>.</sub>

**Comment by richard67** [comment]
> I though this was a bug and did not realise it was a multi-select until I cam here. For me it would be prettier if it were the last filter item, after Filter Target Branch. When it wraps there is a big space down to the last filter item.

As Roland wrote in his comment above: https://github.com/joomla-extensions/patchtester/issues/304#issuecomment-710253028

> In short, I will convert this to core style.

Then it will be same height as the other fields.
