### ISSUE TITLE
patchtester does not work on Postgres: patchtester_pulls_labels does not exist LINE 2

### ISSUE THREAD

**Issue by VladimirAus** [joomla-extensions/patchtester#305]
#### Steps to reproduce the issue

* Install Joomla 4 beta 4 on postgres 12
* Install latest patchtester: https://github.com/joomla-extensions/patchtester/releases/tag/4.0.0
* Go to `/administrator/index.php?option=com_patchtester`

#### Expected result

* com_patchtester page

#### Actual result

Error: `42P01, 7, ERROR: relation "io5nw_patchtester_pulls_labels" does not exist LINE 2: FROM "io5nw_patchtester_pulls_labels" ^`

<img width="1432" alt="Screen Shot 2020-10-17 at 6 36 22 pm" src="https://user-images.githubusercontent.com/1356166/96334507-b31b4a80-10b4-11eb-90a8-ab26d612821f.png">

#### System information (as much as possible)

* PHP  7.3.23 running on Joomla container: https://hub.docker.com/_/joomla
* Latest `postgres:12.4` container: https://hub.docker.com/_/postgres

#### Additional comments

Tested on latest `mysql:5.6` container and it works.

**Comment by richard67** [comment]
@VladimirAus That can happen sometimes, also on MySQL.

Could you check following?

- Uninstall the patchtester wia "System - Manage - Extensions".
- Install the patchtester again.

After that, it should work.

Questions:
- Have you used latest Patchtester 4.0.0 final release?
- You wrote you have installed Joomla, but you haven't installed patchtester? How did that work?
```
Steps to reproduce the issue
- Install Joomla on postgres 12
- Go to /administrator/index.php?option=com_patchtester
```

**Comment by VladimirAus** [comment]
Cheers @richard67.
Updated steps with patch tester.
Testing your suggestion now.

**Comment by VladimirAus** [comment]
Uninstalling and installing did the job.
Thanks @richard67

**Comment by richard67** [comment]
@roland-d This issue is exactly that edge case where the right update SQL script would help to work around it which we discussed on Glip.

**Comment by roland-d** [comment]
Check if you have the folder api/components/com_patchtester. Joomla has a bug where this folder is not removed on uninstall. Later installing patch tester again will do an update install of an install because of that.
