### ISSUE TITLE
[4.0.0] Table 'xxx.jos_patchtester_pulls_labels' doesn't exist

### ISSUE THREAD

**Issue by PhocaCz** [joomla-extensions/patchtester#310]
#### Steps to reproduce the issue
Updated patch tester from previous version, getting following error:
Table 'xxx.jos_patchtester_pulls_labels' doesn't exist

![img](https://i.imgur.com/Mu2t49I.png)

#### Expected result
No error

#### Actual result
Error

#### System information (as much as possible)
Joomla! 4.0.0-beta5

#### Additional comments
BTW - it would be great if the ZIP installation packages 

![img](https://i.imgur.com/WTn7g4R.png)

could include even version as suffix because when saving the files on your PC, it is great to see which version the current package is.

Thank you.

**Comment by roland-d** [comment]
@PhocaCz I did not see this request before but I agree having the version number in the files will be useful. I will make a not of that. The issue of the missing table should no longer be there anymore in the stable release.

**Comment by PhocaCz** [comment]
Ok, thank you for the info.

Jan

**Comment by roland-d** [comment]
@PhocaCz The new release contains the version number in the file :)

**Comment by PhocaCz** [comment]
Great to hear it. Thank you. Jan
