### ISSUE TITLE
Invisible links

### ISSUE THREAD

**Issue by ceford** [joomla-extensions/patchtester#311]
#### Steps to reproduce the issue

View the list of PRs to test

#### Expected result

The View on Github and View on Joomla Issue Tracker should be visible

#### Actual result

Both are are invisible

#### System information (as much as possible)

This is on the nightly build from 2021-01-24 that includes Bootstrap 5.!

#### Additional comments

the style of badge-xxxx needs to be changes to bg-xxxx or both for b/c.

**Comment by richard67** [comment]
Please test #313 .

**Comment by ceford** [comment]
Closed as there is a PR to fix the issue.
