### ISSUE TITLE
Change of color

### ISSUE THREAD

**Issue by ChristineWk** [joomla-extensions/patchtester#312]
#### Steps to reproduce the issue
See screenshot please
sorry, at the moment, problem to add an image. 

#### Expected result
Change of color.

#### Actual result

`.badge {
    display: inline-block;
    padding: .3rem .2rem;
    font-size: .75rem;
    font-weight: 700;
    line-height: 1;
    color: #fff;
    text-align: center;
    white-space: nowrap;
    vertical-align: baseline;
    border-radius: .2rem;
}`

#### System information (as much as possible)
Joomla 4.0.0-beta7-dev

**Comment by ChristineWk** [comment]
[image](https://i.imgur.com/yPqD7E6.png "")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/patchtester/312">issues.joomla.org/tracker/patchtester/312</a>.</sub>

**Comment by chmst** [comment]
Duplicate https://issues.joomla.org/tracker/patchtester/311<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/patchtester/312">issues.joomla.org/tracker/patchtester/312</a>.</sub>
