### ISSUE TITLE
Fetch data stops on 5th page

### ISSUE THREAD

**Issue by sandramay0905** [joomla-extensions/patchtester#324]
#### Steps to reproduce the issue
As title say:

![Bildschirmfoto 2021-04-18 um 09 38 20](https://user-images.githubusercontent.com/78906980/115138041-fcc7fc00-a029-11eb-952e-7cd7ff24290b.png)

#### Expected result
Download of all pull requests.

#### System information (as much as possible)
![image](https://user-images.githubusercontent.com/78906980/115138085-38fb5c80-a02a-11eb-82ba-ea94320f50d6.png)

**Comment by sandramay0905** [comment]
Am i the only one having this problem? 

Would be sad cause i can't test anymore as prebuilt packages can't be downloaded if they are to old.

**Comment by sandramay0905** [comment]
Changed the title as same happen using v4 on Joomla4.

**Comment by roland-d** [comment]
@sandramay0905 For some reason I do not get emails from the patchtester repository. Now I am not aware of any specific issues. When you load the list of patches from Github, does that process complete normally?

**Comment by sandramay0905** [comment]
> does that process complete normally

It stops much earlier than before, only a part (the first five pages) of the pr are loaded.

**Comment by roland-d** [comment]
@sandramay0905 I finally had a chance to test it, but I can see what you see as well. I get a maximum of 5 pages of data. After some debugging I found the problem as well. The word `Link` has been changed to `link`. 

If you want to fix this for your local installation now, you can do the following:
- Open the file administrator/components/com_patchtester/PatchTester/Model/PullsModel.php
- Go to line 538 and change `Link` to `link`
 - Go to line 540 and change `Link` to `link`
 - Save the file
 - Fetch the pull requests

Let me know if that works for you.

**Comment by sandramay0905** [comment]
Can you give me please more information about the lines? I'm working on a site installed by launch.joomla.org and there are no linenumbers shown. Searching for "Link" gave 7 results so i don't know which are the 2 correct to change:

> ![image](https://user-images.githubusercontent.com/78906980/116501761-f2232780-a8b1-11eb-9159-c036ec6ea72f.png)

**Comment by roland-d** [comment]
@sandramay0905 Sure.

These 2 lines is what you look for, they are close to each other:
```
if (isset($pullsResponse->headers['Link']))
```
```
$linkHeader = $pullsResponse->headers['Link'];
```

**Comment by sandramay0905** [comment]
Thanks for help, @roland-d. Patchtester works now as expected, closing issue.

**Comment by sandramay0905** [comment]
@roland-d Is there a timeline for a next release of patchtester? I install every day a new j4 using launch.joomla.org and do the fix too. No work but maybe a new release is coming?

**Comment by roland-d** [comment]
@sandramay0905 The new release is out now.

**Comment by sandramay0905** [comment]
Thank you!
