### ISSUE TITLE
Limit of 30 diff files

### ISSUE THREAD

**Issue by ceford** [joomla-extensions/patchtester#327]
#### Steps to reproduce the issue

Patch any PR that has more than 30 diff files - I hit the problem on 33926

#### Expected result

Some sort of warning - only the first 30 diffs are applied

#### Actual result

No warning and nobody seems to have noticed before

#### System information (as much as possible)

Using Firefox on Mac Catalina with MAMP, PHP8, Eclipse IDE

#### Additional comments

In administrator/components/patchtester/PatchTester/Model/PullModel.php on line 553 the count of files obtained from github is 30. Anything in the PR after that is dropped.

This needs documentation somewhere! Where is the limit set? Can it be altered?

**Comment by roland-d** [comment]
Hello @ceford For some reason I never receive emails from this Github repo so hence a late reply. So I checked the current `master` branch but I do not see any limit. Are you using Patch Tester on Joomla 4?

**Comment by ceford** [comment]
Yes - Joomla 4. I ran into the problem again recently with a patch for 31 files. Eclipse could not do it as a patch either. So I don't test big patches any more.

**Comment by richard67** [comment]
Are you using an API key for authentication at GitHub? If not, maybe there some Limitation by GitHub in such case?

**Comment by ceford** [comment]
Yes - a Github token in the Patch tester options. This was quite a long time ago - I stepped through the PT code to find what was going on. I have now completely forgotten what I did or how i did it.

**Comment by roland-d** [comment]
No worries, I just need to find a large enough PR to test this. For now I could not find one.

**Comment by richard67** [comment]
@roland-d We can use this PR: https://github.com/joomla/joomla-cms/pull/35143 ... it is for 4.1-dev so one has to test that on a 4.1 nightly or alpha installation, but it has 100 changed files and the total change is huge so that should be sufficient.

**Comment by roland-d** [comment]
@richard67 Correct and I have seen what is going on. Github only returns batches of 30 files at a time. So I will need to loop through the links to retrieve all of them.

WIP :)

**Comment by roland-d** [comment]
Ok, with this new PR I was able to test it and fix the issue of PRs with more than 30 files.

**Comment by roland-d** [comment]
I have just released version 4.2.0 that includes this fix. Thank you.
