### ISSUE TITLE
Joomla 4 Patchtester shows wrong link to input credentials

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-extensions/patchtester#330]
#### Steps to reproduce the issue

Install patchtester.
Patchtester asks to type in credentials and offers a link
link leads to

administrator/**_QQ__QQ_**index.php?option=com_config&view=component&component=com_patchtester&returnurl=aW5kZXgucGhwP29wdGlvbj1jb21fcGF0Y2h0ZXN0ZXI=#authentication_**QQ__QQ_**

#### Expected result
index.php?option=com_config&view=component&component=com_patchtester&returnurl=aW5kZXgucGhwP29wdGlvbj1jb21fcGF0Y2h0ZXN0ZXI=#authentication_

#### Actual result
_QQ__QQ_ in front and back of the Link

**Comment by richard67** [comment]
@coolcat-creations Which version of Patchtester on which Joomla version?

**Comment by roland-d** [comment]
@coolcat-creations Thank you for reporting it. This is fixed via issue #333 
I am currently working on a new release of the Patch Tester, please ping me if you have time to give it a test run.
