### ISSUE TITLE
Patchtester doesnot work?

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla-extensions/patchtester#334]
#### Steps to reproduce the issue
I have been testing this issue with Patchtester.
https://github.com/joomla/joomla-cms/pull/35429 
I did get different results as other people.

#### Expected result
If I read the comments about Patchtester and ist is true about the max number of files, can there be a warning if this happens?

**Comment by roland-d** [comment]
Hello Martijn, there is no limit I am aware of. Now I cannot find another PR with more than 30 changes files, so I cannot test this. Let's move this discussion to issue #327  and have the discussion there.
