### ISSUE TITLE
[4] Message "while 4.0 is in development" is obsolete

### ISSUE THREAD

**Issue by chmst** [joomla-extensions/patchtester#338]
#### Steps to reproduce the issue

![grafik](https://user-images.githubusercontent.com/1035262/150699956-9edb7d0f-fa0f-4f06-b8a4-7e3023e5f1f6.png)
As J4 is stable, the message is not longer correct

**Comment by richard67** [comment]
As far as I know this has been fixed already, there just hasn’t been made a new release yet.

**Comment by richard67** [comment]
See #332 .

**Comment by chmst** [comment]
thank you :)
