### ISSUE TITLE
[4] No search possible in the search field

### ISSUE THREAD

**Issue by chmst** [joomla-extensions/patchtester#339]
#### Steps to reproduce the issue
![grafik](https://user-images.githubusercontent.com/1035262/150700065-3d293ede-1942-4606-b3ca-d9048aa8ad84.png)

The tooltip blocks the input in the search field

**Comment by richard67** [comment]
Should have been solved by #336

**Comment by richard67** [comment]
@roland-d Could you make a new release of the patchtester so we don’t get reported issues which are solved already and just not have been released? Thanks in advance.

**Comment by roland-d** [comment]
@richard67 Yes, I will do the release soon.

**Comment by richard67** [comment]
This issue should be closed then.
