### ISSUE TITLE
Bad Target Branch label colors - inaccessible.

### ISSUE THREAD

**Issue by ceford** [joomla-extensions/patchtester#340]
#### Steps to reproduce the issue

Select a Filter Target Branch from the Filter Options

#### Expected result

A legible label

#### Actual result

The Target Branch label is coloured black on dark blue - unreadable. Also, labels with white on blue turn to black on blue on hover.

#### System information (as much as possible)

Joomla 4.2-dev PHP 8

**Comment by roland-d** [comment]
@ceford I think this is no longer an issue? Here is what I see:
![image](https://user-images.githubusercontent.com/359377/194725500-7256b8fe-4f93-4150-93b3-e375dad7f77d.png)

Do you still see all the colors in the dropdown? If so, can you post a screenshot of what you see?

**Comment by ceford** [comment]
With a recent 4.2.3 install and a new install of Patchtester I see that hover over either if the View buttons produces black text on blue background:

![image](https://user-images.githubusercontent.com/1560390/194729431-59ba4b23-4ab2-4500-8d11-4037e387e869.png)

**Comment by roland-d** [comment]
Hello @ceford Ah I see what you mean. I have no design skills, can you or do you know someone who can provide a pull request or tell me what changes are needed, I can implement them.

**Comment by ceford** [comment]
One way to tackle the problem is to change the link class to match the Apply Patch button. So, for example:

<a href="https://github.com/joomla/joomla-cms/pull/38920" target="_blank" class="btn btn-sm btn-primary">View on GitHub</a>

That produces a strange hover behaviour on hovering over the patch Title. That is caused by this empty span:
<div role="tooltip" id="tip0">
</div>

Can that go too?

**Comment by N6REJ** [comment]
@roland-d I'll try to remember to fix that tomorrow.

**Comment by N6REJ** [comment]
pr created #351

**Comment by roland-d** [comment]
Closing this as PR #351 has been merged.
