### ISSUE TITLE
An error has occurred while fetching the data from GitHub.

### ISSUE THREAD

**Issue by Franzwohlkoenig** [joomla-extensions/patchtester#346]
#### Steps to reproduce the issue
While fetching data got:

<img width="587" alt="Untitled" src="https://user-images.githubusercontent.com/89642616/184065398-f22e93c4-ba41-4290-a725-543e0faeae02.png">

#### Expected result
No error.

#### Actual result
No data fetched.

#### System information (as much as possible)

Patchtester 4.2.1, Joomla 4.1.5

#### Additional comments
--

**Comment by N6REJ** [comment]
confirmed
![image](https://user-images.githubusercontent.com/1850089/184088774-bd885357-92bc-4c85-96cc-98bb2191afda.png)
