### ISSUE TITLE
Deprecated mb_strlen() with php 8.1+

### ISSUE THREAD

**Issue by N6REJ** [joomla-extensions/patchtester#350]
#### Steps to reproduce the issue
after setting up your github token, fetch data.  You will see 3 errors.  This is normall the second error listed.

```Deprecated: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in E:\Bearsampp\www\j4\libraries\vendor\joomla\string\src\phputf8\mbstring\core.php on line 24```

#### Expected result

no errors displayed, data is fetched properly

#### Actual result

```
An error has occurred while fetching the data from GitHub.

Deprecated: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in E:\Bearsampp\www\j4\libraries\src\MVC\Model\ListModel.php on line 543

Deprecated: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in E:\Bearsampp\www\j4\libraries\vendor\joomla\string\src\phputf8\mbstring\core.php on line 24

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in E:\Bearsampp\www\j4\libraries\src\HTML\Helpers\StringHelper.php on line 132
{"success":true,"message":"Processing page 2 of 3 pages of GitHub data","messages":null,"data":{"complete":false,"page":2,"lastPage":3}}

```
NOTE: other errors are corrected in 
https://github.com/joomla/joomla-cms/pull/38917 ( Fixes php 8.1 strtoupper deprecation error )
https://github.com/joomla/joomla-cms/pull/38918 ( Fixes str_replace deprecation warning in php 8.1 )

#### System information (as much as possible)

J! 4.2-dev & patch_tester 4.2.1

#### Additional comments

@roland-d I was told by @Hackwar  & @HLeithner that this pr fixes the issue the wrong way. https://github.com/joomla-framework/string/pull/42  Can you address this please.

**Comment by roland-d** [comment]
@N6REJ Closing this in favor of #341, so let's keep it in one place.
