### ISSUE TITLE
Joomla [5.0]

### ISSUE THREAD

**Issue by chmst** [joomla-extensions/patchtester#353]
#### Steps to reproduce the issue
Install Patchtester on a Joomla 5.0 and try to fetch data: 

![grafik](https://github.com/joomla-extensions/patchtester/assets/1035262/9e41f2f8-97cf-417d-96e4-84a5ea12daa4)

**Comment by deltapapa01** [comment]
Confirm, when push RESET i get this error:

`PatchTester\Model\PullModel::__construct(): Argument #2 ($db) must be of type ?JDatabaseDriver, Joomla\Database\Mysqli\MysqliDriver given, called in /html/cms/administrator/components/com_patchtester/PatchTester/Controller/ResetController.php on line 42`

**Comment by bayareajenn** [comment]
Same. I can confirm in 5.0.0a4. Thanks for opening an issue Christiane.
![image](https://github.com/joomla-extensions/patchtester/assets/5952595/0fb5570e-e791-4a86-a573-6579c24bdd14)
What do you reckon @roland-d?

**Comment by roland-d** [comment]
@chmst @deltapapa01 @chmst @alikon I put out  a new release of the patch tester, version 4.2.2 that should address these issues and a few more. Care to give it a try?

**Comment by bayareajenn** [comment]
@roland-d So much better. It installs now and will take my token and fetch issues. YAY!!

However, I can only load five pages of issues. Is that by design? So if I want to test issue 41104, I cannot. 
![image](https://github.com/joomla-extensions/patchtester/assets/5952595/2a46c819-ca38-452a-adf0-b0a2a3dae800)

Thoughts?

**Comment by roland-d** [comment]
@bayareajenn Do you get any error? Perhaps an error while loading the issues? When I fetch data I get 14 pages of issues. You can check the requests by opening the developer tools in your browser (usually by pressing F12 or right click and choose Inspect). On the network tab you will see the requests go by as you fetch issues. These should all end in a status of 200.

I wonder if anybody else has this issue.

**Comment by chmst** [comment]
I got 14 pages - xampp, win and  php 8.2. Could the php version make a difference?

**Comment by bayareajenn** [comment]
@roland-d Everything in the network tab has a status of 200 when I fetch issues. I'll figure it's just me and we can carry on. I can install the ci packages with the pr when I need to test something. As long as normal people at PB&F can load all the issues, all good. Thank you for your quick work on the package and having it ready for J5!! You rule!! <3

**Comment by roland-d** [comment]
@bayareajenn 5 pages seem to indicate only 1 step completed. If you know how, can you check the response in the network tab of the first page indexing. Curious to know what it says.

Do you see 3 pages being indexed or just 1?

**Comment by bayareajenn** [comment]
I PMd you @roland-d cuz I think I'm just seeing 1 page indexed but I am not great at reading the network tab.

**Comment by bayareajenn** [comment]
Roland and I chatted about this and have determined that the response issue only showing me five pages is an issue on my server. All good! Let's move on! Thanks Rolando!!! <3
