### ISSUE TITLE
[4.3.1]: The Filter RTC Patches 'No' filter does not work...

### ISSUE THREAD

**Issue by exlemor** [joomla-extensions/patchtester#371]
#### Steps to reproduce the issue
I have Joomla 5.1.0-beta1 installed (i'm testing Patches for 5.1 RC).

I am in the Joomla Patch Tester and I want to filter my view to only see 5.1-dev and RTC Patches set to: No.

#### Expected result
I see a list that only contains 5.1-dev and Ready to Commit: No

#### Actual result
I see a list that only contains 5.1-dev and Ready to Commit: Yes and No. ;(

Ironically, if you select Filter RTC: Yes, it works perfectly and shows only Yes results...

#### System information (as much as possible)
PHP 8.2.17, 
MySQL 8.0.36
Joomla 5.1-dev 

#### Additional comments
![Joomla-Patch-Tester-RTC-set-to-Yes](https://github.com/joomla-extensions/patchtester/assets/2597232/22abb2c9-c12a-4168-afb1-604f34631db3)

![Joomla-Patch-Tester-RTC-set-to-No](https://github.com/joomla-extensions/patchtester/assets/2597232/b10b139e-11c3-4559-9e50-68ae096ec597)

**Comment by alikon** [comment]
should be fixed in https://github.com/joomla-extensions/patchtester/pull/365

**Comment by exlemor** [comment]
Hi @alikon, thanks, but stupid question since #365 says it is merged back in Sept. 2023 does that mean that a new version needs to be released of Joomla Patch Tester that will include this fix or that the fix at that time, missed this issue?

**Comment by alikon** [comment]
> does that mean that a new version needs to be released of Joomla Patch Tester that will include this fix

yes

**Comment by fgsw** [comment]
Should the issue be closed as there is the (merged) pull request #365?

**Comment by roland-d** [comment]
Hi, a new release has just been put out with this fix included.
