### ISSUE TITLE
Help file for Options is not set

### ISSUE THREAD

**Issue by ceford** [joomla-extensions/patchtester#372]
#### Steps to reproduce the issue

From the Patchtester page select the Options button.
In the Options page select the Help button.

#### Expected result

There should be a Help page (or no Help button)

#### Actual result

The Help window gives a 404.

#### Additional comments

There is a Help page for Joomla 4. I created a copy for Joomla 5 today.
To use these pages this line needs to be added on line 3 of administrator/components/com_patchtester/config.xml

`	<help key="Components_Patch_Tester_Options"/>`

**Comment by roland-d** [comment]
Hello @ceford ,

Thank you for that. I have added that line to the `config.xml` as I am preparing a new release of the Patch Tester that is refactored to use the Joomla way of doing things.
