### ISSUE TITLE
FAQ : error msg on WAMPserver : Unable to find the socket transport 'ssl'

### ISSUE THREAD

**Issue by garstud** [joomla-extensions/patchtester#42]
One member of my PBF session has got this error when installing **com_patchtester 2.0.0 Beta**.
He has a WampServer with PHP 5.3.13.
After some checks in his PHP configuration, we find that its **Socket Transport has no "SSL".**

**Solution :**
- in the WampServer menu
- activate the PHP module **openssl**
- then go to the Joomla admin menu : System > Sytem information > PHP information
- you will see that Socket Transport has now 'SSL' features :

![socket_transport-phpconfig](https://cloud.githubusercontent.com/assets/970021/4670336/35550fb4-5576-11e4-9cc2-af94564b9fb4.png)

**Comment by Rai-Ka** [comment]
Same problem with XAMPP 1.8.1. 
White screen after trying to use the newly installed vers. 2.0.0.beta.
ErrorMessage:
Fatal error: Call to a member function get() on a non-object in G:\xampp\htdocs\joomla-git\administrator\components\com_patchtester\PatchTester\View\Pulls\tmpl\default.php on line 17
<Stacktrace......>
End ErrorMessage

David Jordan found out that the openssl.dll wasn't enabled in my php.ini:
;extension=php_openssl.dll

After enabling and restarting of the apacheserver everything works...

**Comment by mbabker** [comment]
If I'm not mistaken, the wiki section of the repo can be updated by anyone.  Feel free to update the [FAQ](https://github.com/joomla-extensions/patchtester/wiki/FAQ) with these notes.
