### ISSUE TITLE
Uninstalling Patch results in PHP Fatal Error

### ISSUE THREAD

**Issue by haydenyoung** [joomla-extensions/patchtester#45]
To reproduce:
- From Patch Tester com, install patch from 4718,
- Uninstall patch

Results in error:

Fatal error: Class 'JSubMenuHelper' not found in /var/www/html/pbf33/administrator/modules/mod_submenu/mod_submenu.php on line 12

Checking administrator/includes/toolbar.php shows class JSubMenuHelper exists and refreshing the page rectifies the problem.

**Comment by mbabker** [comment]
I've yet to be able to duplicate this.  If it's still an issue, note it again and provide more details please.
