### ISSUE TITLE
Installing on postgres ;(

### ISSUE THREAD

**Issue by brianteeman** [joomla-extensions/patchtester#47]
Trying to install on postgres gives a sql error

 Database query failed (error # %s): %s SQL=SELECT COUNT(*) FROM "s376f_patchtester_pulls" AS "a" LEFT JOIN "s376f_patchtester_tests" AS "t" ON t.pull_id = a.pull_id WHERE ("a"."title" LIKE '%4815%') OR ("a"."pull_id" LIKE '%4815%')

**Comment by alikon** [comment]
can be closed as the fix #75 has been merged
