### ISSUE TITLE
One more view

### ISSUE THREAD

**Issue by dgt41** [joomla-extensions/patchtester#55]
Can we add one more view with all the applied patches?

The reason I am asking for this is that if somebody applies a PR and later on the patch gets accepted the patch will not reveal itself in the list, and therefore is kinda hard to revert the patch from the environment. 
As far as I checked there is a table in the db where the applied patches are stored, so it won’t be that hard to make one more view with a list of all this. (the data column also got the title, etc…)

**Comment by mbabker** [comment]
In the current dev head, it is possible to filter on applied patches.  So
it should be good from there.

**Comment by mbabker** [comment]
Tagged 2.0.0.beta2 with ability to sort by applied status and filter on these items.  I think this is good enough.

**Comment by dgt41** [comment]
Thanks @mbabker!
