### ISSUE TITLE
Don't throw an exception when you can't connect to server

### ISSUE THREAD

**Issue by wilsonge** [joomla-extensions/patchtester#57]
I've seen a couple of people report when they get an error because username/password is incorrect on github they struggle to edit their passwords again (they have to go access the config via global configuration which clearly isn't ideal!)

Can we not display an "in component" error rather than blocking all access to the component?

**Comment by mbabker** [comment]
With all the changes in how data is fetched and the added error handling, this should be resolved and no longer an issue.
