### ISSUE TITLE
Language String Missing after Install

### ISSUE THREAD

**Issue by mtmeyrick** [joomla-extensions/patchtester#68]
After installing beta2 of Patch Tester, the install success message displays as language string.

COM_INSTALLER_INSTALL_SUCCESS

**Comment by mbabker** [comment]
What Joomla version and can you make sure that the key is actually present in `administrator/language/en-GB/en-GB.com_installer.ini`?  I just tried 3 installs using the current staging branch on the CMS and got the right message.

**Comment by mtmeyrick** [comment]
Have checked for language string before reporting and tried on two different installations, on both installations threw up the error, have just checked on another two and seem to be work as expected. 

Recon this can be closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/patchtester/68">issues.joomla.org/patchtester/68</a>.</sub>
