### ISSUE TITLE
Cannot use due to Two-Step Authentication

### ISSUE THREAD

**Issue by hans2103** [joomla-extensions/patchtester#70]
Due to company security restrictions I have Github two-step authentication activated
When I add my credentials (username & password) to com_patchtester I receive the following error:

> An error has occurred.
 401 Must specify two-factor authentication OTP code.

**Comment by mbabker** [comment]
It's a known issue.  To use an account that has two factor authentication enabled, you'll have to create a personal access token on GitHub (at https://github.com/settings/applications) and store that token in the "GitHub Token" option in the component's config.

**Comment by hans2103** [comment]
thx... created pull-request (https://github.com/joomla-extensions/patchtester/pull/71) for documentation
