### ISSUE TITLE
Ordering issues for some installs

### ISSUE THREAD

**Issue by davdebcom** [joomla-extensions/patchtester#72]
During the Dutch PBF in Dordrecht a user told me about this error, but I don't have more information. Just sending it to you so you know about it. After install the had an error referring to 
administrator/components/com_patchtester/PatchTester/View/Pulls/tmpl/default.php
line 17-20

Later he enabled OpenSSL and downgraded to the beta (he was using beta2) and it was gone. 

That's all I know.

```
$listOrder     = $this->escape($this->state->get('list.ordering'));
$listDirn      = $this->escape($this->state->get('list.direction'));
$filterApplied = $this->escape($this->state->get('filter.applied'));
$sortFields    = $this->getSortFields();
```

**Comment by mbabker** [comment]
Can you get any other info from the person?  There's very little to work with here.

**Comment by davdebcom** [comment]
I suggest you close it then, PBF has ended so no way to find out.
