### ISSUE TITLE
Sort by status missing

### ISSUE THREAD

**Issue by peterpeter** [joomla-extensions/patchtester#76]
Hi
I'm starting using the patchtester this week. Really a great work! But...
To see if there are still patches applied in my installation from my last test session/evening it would be helpful to be able to sort the 'status' column.

Sure, I could set the pagination set to 'all' and scroll down or use the browsers search (ctrl+f), but in my patchtester-instance the paginations 'list all' wont work somehow (J 3.4).

And again: concrats to this wonderful tool, it leads my to test patches on a regular basis from now.

**Comment by mbabker** [comment]
With the current release, the first filter allows you to filter on patches that have or haven't been applied.

![screen shot 2015-03-08 at 12 40 19 pm](https://cloud.githubusercontent.com/assets/368545/6546595/4c28525c-c590-11e4-87f1-3d80bce0c60b.png)

**Comment by peterpeter** [comment]
Ok, thanks Michael, I'll update and try. I grabbed the 'beta' instead of 'beta2', but a link in the docu on
https://docs.joomla.org/Component_Patchtester_for_Testers#Download_com_patchtester
leads the reader's to
https://github.com/joomla-extensions/patchtester/releases/tag/2.0.beta
wich is obvioulsy outdated.
