### ISSUE TITLE
Fatal error: Class 'PatchTester\Model\JText'

### ISSUE THREAD

**Issue by jessicadunbar** [joomla-extensions/patchtester#79]
I tried to apply https://github.com/joomla/joomla-cms/pull/6447 and received the following error
Fatal error: Class 'PatchTester\Model\JText' not found in /home/example/public_html/example.com/fresh/administrator/components/com_patchtester/PatchTester/Model/PullModel.php on line 168

**Comment by mbabker** [comment]
The JText error is fixed already.  As for that patch, it won't apply with the patch tester; it doesn't work with binary files right now.
