### ISSUE TITLE
Binary Files

### ISSUE THREAD

**Issue by brianteeman** [joomla-extensions/patchtester#8]
The patch tester (i'm assuming uses diff) which ignores binary files. We just wasted 3 hours debugging an issue with a pull request that had ttf and woff fonts which are binary and were not getting applied.

Either the patchtester needs a way to handle binary files OR at a minimum give a notice that filex was not copied

**Comment by mbabker** [comment]
I've added a warning if binary files are included in a patch.  I can't think of a way to correctly handle these so for now it's just completely unsupported.
