### ISSUE TITLE
Error: Unable to find install package - Joomla! 3.4.1

### ISSUE THREAD

**Issue by Yiannistaos** [joomla-extensions/patchtester#80]
Hello guys,

Trying install the patchtester on the latest version of joomla 3.4.1, but the below messages have been displayed.

Warning:
JInstaller: :Install: Can't find Joomla XML setup file.

Error:
Unable to find install package
![extension manager install](https://cloud.githubusercontent.com/assets/8467542/6786429/dee61b50-d194-11e4-955b-ee77642b03b8.png)

Thanks.

**Comment by dgt41** [comment]
@Yiannistaos go to releases and d/l the latest version. here:
![screen shot 2015-05-06 at 4 46 22](https://cloud.githubusercontent.com/assets/3889375/7494337/ae988986-f40f-11e4-99c4-cf9112d3a65d.png)


 Most probably you d/l a zip of the dev code, which of course is not just the component

**Comment by Yiannistaos** [comment]
@dgt41 it works now!

The component works fine on a live server, but it doesn't works on a local server with xampp (below are my xampp's version).

###### ApacheFriends XAMPP version 1.7.7 ######

  + Apache 2.2.21
  + MySQL 5.5.16 (Community Server)
  + PHP 5.3.8 (VC9 X86 32bit thread safe) + PEAR
  + XAMPP Control Panel Version 2.5 from www.nat32.com 
  + (BETA) XAMPP Control Panel Version 3.0.2 by Steffen Strueber (not in the USB & lite version)
    see http://www.apachefriends.org/f/viewtopic.php?f=16&t=46743
  + XAMPP Security
  + OpenSSL 1.0.0e
  + phpMyAdmin 3.4.5
  + ADOdb 5.14
  + Mercury Mail Transport System v4.62 (not in the USB & lite version)
  + FileZilla FTP Server 0.9.39 (not in the USB & lite version)
  + Webalizer 2.23-04 (not in the USB & lite version)
  + Perl 5.10.1 (not in the USB & lite version)
  + Mod_perl 2.0.4 (not in the USB & lite version)
  + Tomcat 7.0.21 (not in the USB & lite version)

**Comment by zero-24** [comment]
@Yiannistaos you can't install form github/ssl on xampp via "Install from URL". How do you try to install? Per download and upload & install?

**Comment by Yiannistaos** [comment]
@zero-24 The installation has been completed successfully on Xampp, but the problem is the blank results there.
![xampp](https://cloud.githubusercontent.com/assets/8467542/7561770/6d0c2524-f7d7-11e4-9ec5-ebf07dc3e348.png)
![test administration joomla patch tester](https://cloud.githubusercontent.com/assets/8467542/7561771/6d11ee8c-f7d7-11e4-882a-b26278726e0d.png)

**Comment by zero-24** [comment]
@Yiannistaos can you have a look into the php.ini please make sure you have https support enabled (openssl).

Also please try to set the `Errorreporting` to `Maximum` or `Development` :smile:

**Comment by Yiannistaos** [comment]
@zero-24 everything is fine now after installing and enabling the "openssl" extension in xampp.

Openssl is disabled in xampp by default, so if someone wants to enable it, may follow the below easy steps:

1. Check if php_openssl.dll file exists in [xampp_folder]/php/extfolder. If you have successfully installed XAMPP before, you would have it there.

2. In [xampp_folder]/php/php.ini file, look for openssl.dll. It should be something like ;extension=php_openssl.dll. Uncomment the line by removing semicolon “;”.

3. If you cannot find the line, don’t worry if you have php_openssl.dll file under ext folder(see first point). If you have the file, add the following code after the list of extension. [PHP_OPENSSL] extension=php_openssl.dll

4. Save the file and exit the editor

5. In XAMPP control panel, restart the Apache.

6. That is done.

Thank you guys, @zero-24 @dgt41 :+1:

**Comment by smz** [comment]
Isn't there a way to check if openssl is enabled and issue a warning/error in case it isn't?

**Comment by dgt41** [comment]
Something like this maybe?
```php
 if(!extension_loaded('openssl'))
    {
        throw new Exception('MSG NO SSL extension loaded');
    }
```

**Comment by mbabker** [comment]
OpenSSL is checked [here](https://github.com/joomla-extensions/patchtester/blob/master/administrator/components/com_patchtester/PatchTester/View/Pulls/PullsHtmlView.php#L69-L72) and should raise an error.

Also, Joomla nor the patch tester should be working on the XAMPP environment if it's running PHP 5.3.8; there's a 5.3.10+ requirement.

**Comment by smz** [comment]
@mbabker 
... then maybe the check should be moved to some other place earlier on?

**Comment by mbabker** [comment]
If I moved it any earlier it'd be in the patchtester.php entry point file.  That's actually pretty early in the component cycle, after the controller has instantiated the model and view classes but before the user is able to even attempt fetching data from GitHub.

BTW, the blank screen thing means it was hitting the error layout, someone just managed to miss an `echo` statement when rendering it...

**Comment by smz** [comment]
> BTW, the blank screen thing means it was hitting the error layout, someone just managed to miss an echo statement when rendering it...

Got it! :+1: 

... but what is it your https://github.com/joomla-extensions/patchtester/commit/cbb1652f4adbbefa2ac0af327fe25bbd81efaa40 commit? I don't see it as a PR...

**Comment by mbabker** [comment]
It's committed to the master branch already.
