### ISSUE TITLE
Javascript error data fetching when github password contains "@"

### ISSUE THREAD

**Issue by vinespie** [joomla-extensions/patchtester#87]
### # Steps to reproduce the issue

1- Click "Options"
2- In field "GitHub Account Password", insert "@"
3- Go to "Joomla! Patch Tester" and fetch data

#### Expected result
Fetching data from github

#### Actual result
Javascript error when fetching

ReferenceError: Joomla is not defined in fetcher.js line 62
jQuery('#patchtester-progress-header').text(Joomla.JText._('COM_PATCHTESTER_FETC...

![2015-05-09 14_37_22](https://cloud.githubusercontent.com/assets/5129879/7550344/9a16ec72-f65e-11e4-8cf4-df073a102942.png)

**Comment by mbabker** [comment]
It's a known issue in the Joomla core, please follow https://github.com/joomla/joomla-cms/pull/6734.
