### ISSUE TITLE
Fetch Data don't work on beta3

### ISSUE THREAD

**Issue by zero-24** [joomla-extensions/patchtester#92]
### How to test

- install current beta3 (i have also tryed to uninstall and re install)
- access com_patchtester
- try the "fetch data" button
- see:
![fetching_github_data_beta3](https://cloud.githubusercontent.com/assets/2596554/7555117/0606b14a-f742-11e4-9204-569ad02f22b2.PNG)

`Uncaught TypeError: Cannot read property 'options' of null`
It looks like we have JS issues?

If i than remove this part: https://github.com/joomla-extensions/patchtester/blob/master/administrator/components/com_patchtester/PatchTester/View/Pulls/tmpl/default.php#L31-42

I get one issue more.
`Uncaught TypeError: Cannot read property 'task' of null`

If I remove also this code: https://github.com/joomla-extensions/patchtester/blob/master/administrator/components/com_patchtester/PatchTester/View/Pulls/tmpl/default.php#L26-29

Fetching the data works but without the filter.

**Comment by mbabker** [comment]
Can't duplicate it.  Tried with current staging and the beta 3 packages as both an anonymous user and the `jissues-bot` account and all worked just fine.  Tested on both templates.

**Comment by zero-24** [comment]
ah found it. Sorry you need to enable the multilanguage module for the admin too to get the error. If it is disabled all work good.

But i don't understand why we have errors with the module enabled.

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/pull/6918

**Comment by zero-24** [comment]
Thanks :+1: works here. Closing here as it is a issue in the CMS.
