### ISSUE TITLE
Postgres install fails

### ISSUE THREAD

**Issue by brianteeman** [joomla-extensions/patchtester#95]
Trying to install with postgres

> Error inserting pull request data into the database: SQL=INSERT INTO otnhu_patchtester_pulls ....

**Comment by brianteeman** [comment]
Sorry should have said - it installs fine - that error is from when you are fetching Github Data

**Comment by mbabker** [comment]
Chased this down to an issue with a description being longer than the column allows.  Descriptions should be getting truncated to 100 characters with `JHtmlString::truncateComplex()` and the column allows a max of 150 characters, but the description for https://github.com/joomla/joomla-cms/pull/6773 ended up at 170 characters.

```sh
    {
        "length": 170,
        "description": "## PR Summary\r\n\r\nIn display method of many backend controllers, we are having this code:\r\n\r\n````php\r\n$this->setError(JText::sprintf('JLIB_APPLICATION_ERROR_UNHELD_ID',..."
    },
```

**Comment by brianteeman** [comment]
Great
