### ISSUE TITLE
Cannot apply valid patch

### ISSUE THREAD

**Issue by softforge** [joomla-extensions/patchtester#99]
#### Steps to reproduce the issue

Installed these extensions:

Akeeba Backup
No Number Extension Manager
Shadowbox Media Manager
Patch Tester b3 :)

Tried to apply patch 7129 - Rebased download system/environment information

#### Expected result

Patch applied

#### Actual result

*Message*
There are no files to patch from this pull request. This may mean that the files in the pull request are not present in your installation.

#### System information (as much as possible)

Joomla v3.4.2-dev (staging)
PHP v5.4.40

#### Additional comments

Abuse about Michael (from George)... ;)

**Comment by zero-24** [comment]
hmm i can't confirm that for 7129. Can you try to `Fetch Data` again?

**Comment by wilsonge** [comment]
We just got the same issue again when try to apply https://github.com/joomla/joomla-cms/pull/7052 as well. I'll try and run it again.

**Comment by zero-24** [comment]
hmm this works on my end too.

**Comment by mbabker** [comment]
I can't duplicate it either.  Either with the tagged release or the current dev head.  With or without GitHub credentials, behaves as expected.

**Comment by wilsonge** [comment]
I believe it was fixed with https://github.com/joomla/joomla-cms/commit/ccb4c1fc7d0b694208a00dd7c8861718a708f87f - although not 100%
